// Auto-generated by scripts/generate-articles-data.mjs — DO NOT EDIT
// Generated at: 2026-07-07T13:25:06.958Z

export interface ArticleMeta {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  cover?: string;
  tags: string[];
  author?: string;
}

export interface Article extends ArticleMeta {
  content: string;
}

export const articlesData: Record<string, Article[]> = {
  "en": [
    {
      "slug": "game-jam-2026-review",
      "title": "Game Jam 2026 Shenyang Recap",
      "date": "2026-03-01",
      "excerpt": "A recap of Global Game Jam 2026 Shenyang site — 48 hours of creative marathon that produced over 20 game prototypes.",
      "tags": [
        "Game Jam",
        "Event Recap",
        "Indie Games"
      ],
      "author": "Permafrost Echo",
      "content": "\n## Event Overview\n\nGlobal Game Jam 2026 Shenyang site concluded successfully in February 2026. As part of the world's largest game creation marathon, the Shenyang site attracted over 150 developers from across Northeast Asia.\n\n## Highlights\n\n### 48-Hour Creative Sprint\n\nParticipants created game prototypes from scratch in just 48 hours. This year's theme was \"**Echo**\", perfectly aligning with Permafrost Echo's brand philosophy.\n\n### Featured Works\n\nThe Game Jam produced 22 game prototypes across various genres:\n\n| Genre | Count | Notable Works |\n|-------|-------|---------------|\n| Platformer | 6 | Echo Jump, Mirror World |\n| Puzzle | 5 | Sound Maze, Frequency Resonance |\n| Narrative | 4 | The Last Echo, Memory Fragments |\n| Action | 4 | Sonic Chronicles, Resonance Strike |\n| Others | 3 | Echo Farm, Rhythm Garden |\n\n## Looking Forward\n\nPermafrost Echo will continue hosting Game Jam events, with the next edition planned for Fall 2026. We look forward to more developers joining us in growing the Northeast Asia indie game ecosystem!\n\n---\n\n*Photos: Permafrost Echo Team*  \n*Editor: Permafrost Echo Content Team*\n"
    },
    {
      "slug": "ssca-2026-announcement",
      "title": "SSCA 2026 Shenyang Indie Game Showcase Announcement",
      "date": "2026-01-15",
      "excerpt": "Permafrost Echo announces that SSCA 2026, the Shenyang Indie Game Creators Alliance annual showcase, will be held on March 15 with an upgraded scale. We look forward to your participation!",
      "tags": [
        "SSCA",
        "Event Announcement",
        "Indie Game"
      ],
      "author": "Permafrost Echo",
      "content": "\n## Event Announcement\n\nPermafrost Echo is proud to announce that **SSCA 2026** (Shenyang Indie Game Creators Alliance Annual Showcase) will be held on **March 15, 2026** in Shenyang.\n\n## Event Highlights\n\n### Scaled Up\n\nCompared to the first SSCA 2025, this year's event has been fully upgraded:\n\n- **Exhibited Titles**: Increased from 8 to 12+\n- **Participants**: Expected to exceed 500\n- **Coverage**: Expanded from Shenyang to the entire Northeast Asia region\n- **Partners**: 5 new brand sponsors added\n\n### Event Content\n\n1. **Game Showcase** — 12+ indie games available for hands-on demo\n2. **Developer Talks** — 5 keynote speeches and roundtable discussions\n3. **Business Matchmaking** — One-on-one meetings between publishers and developers\n4. **University Alliance Forum** — Exchange and collaboration among representatives from 12 universities\n5. **Award Ceremony** — Annual Best Indie Game Selection\n\n### Exhibited Titles (Partial)\n\n- 🎮 *Doomsday Traveler* — Post-apocalyptic survival adventure\n- 🎮 *Phantom Blade Chronicles* — Cyber-Chinese action RPG\n- 🎮 *Star Garden* — Healing idle simulation\n- 🎮 *Void Chess* — Hardcore strategy chess\n- 🎮 *Gravity Shift* — Innovative puzzle platformer\n- 🎮 *Frost Punk Tales* — Northeast industrial aesthetic narrative adventure\n\n## Registration Information\n\n**Event Date**: March 15, 2026, 10:00 AM – 6:00 PM  \n**Venue**: Shenyang (specific location TBA)  \n**Registration**: Follow the WeChat official account \"冻土回声\" for the registration link\n\n## Partners\n\nThank you to the following partners for supporting SSCA 2026:\n\n- AutoFull — Official esports chair partner\n- ASUS — Hardware support\n- EVNIA — Monitor sponsor\n- Bilibili — Livestream platform partner\n\n---\n\n*We look forward to seeing you at SSCA 2026!*\n"
    }
  ],
  "zh": [
    {
      "slug": "game-jam-2026-review",
      "title": "Game Jam 2026 沈阳站回顾",
      "date": "2026-03-01",
      "excerpt": "回顾 Global Game Jam 2026 沈阳站的精彩瞬间，48小时创作马拉松，诞生了超过20款创意游戏原型。",
      "tags": [
        "Game Jam",
        "活动回顾",
        "独立游戏"
      ],
      "author": "冻土回声",
      "content": "\n## 活动概览\n\nGlobal Game Jam 2026 沈阳站于 2026年2月圆满落幕。作为全球最大的游戏创作马拉松活动的一部分，沈阳站吸引了来自东北亚各地的 150+ 名开发者参与。\n\n## 精彩瞬间\n\n### 48小时极限创作\n\n在短短 48 小时内，参赛者们从零开始创作游戏原型。今年的主题是\"**Echo**\"（回声），与冻土回声的品牌理念完美契合。\n\n### 作品亮点\n\n本次 Game Jam 共产出 22 款游戏原型，涵盖以下类型：\n\n| 类型 | 数量 | 代表作品 |\n|------|------|----------|\n| 平台跳跃 | 6 | 《回声跳跃》《镜面世界》 |\n| 解谜游戏 | 5 | 《声音迷宫》《频率共振》 |\n| 叙事冒险 | 4 | 《最后的回声》《记忆碎片》 |\n| 动作射击 | 4 | 《音波战记》《共振打击》 |\n| 其他 | 3 | 《回声农场》《音律花园》 |\n\n### 获奖作品\n\n**最佳游戏奖**：《声音迷宫》— 通过声音频率解谜的创新玩法\n\n**最佳美术奖**：《镜面世界》— 精美的赛博国风视觉风格\n\n**最佳创意奖**：《频率共振》— 多人协作的声音共振机制\n\n## 参与者反馈\n\n> \"这是我第三次参加沈阳 Game Jam，每次都能感受到这个社区的热情和创造力。冻土回声为东北地区的独立游戏开发者提供了一个绝佳的交流平台。\" — 参赛者张明\n\n> \"48小时的创作马拉松虽然辛苦，但看到自己的作品从无到有，那种成就感无可替代。\" — 参赛者李雪\n\n## 展望未来\n\n冻土回声将继续举办 Game Jam 活动，下一届预计在 2026 年秋季举行。我们期待更多开发者加入，一起推动东北亚独立游戏生态的发展！\n\n---\n\n*摄影：冻土回声团队*  \n*编辑：冻土回声内容组*\n"
    },
    {
      "slug": "ssca-2026-announcement",
      "title": "SSCA 2026 沈阳独立游戏发布会公告",
      "date": "2026-01-15",
      "excerpt": "冻土回声宣布 SSCA 2026 沈阳独立游戏创作者联盟发布会将于3月15日举行，规模升级，期待您的参与！",
      "tags": [
        "SSCA",
        "活动公告",
        "独立游戏"
      ],
      "author": "冻土回声",
      "content": "\n## 活动公告\n\n冻土回声荣幸宣布，**SSCA 2026**（沈阳独立游戏创作者联盟年度发布会）将于 **2026年3月15日** 在沈阳举行。\n\n## 活动亮点\n\n### 规模升级\n\n相比首届 SSCA 2025，今年的活动规模全面升级：\n\n- **参展作品**：从 8 款增加到 12+ 款\n- **参与人数**：预计超过 500 人\n- **覆盖范围**：从沈阳扩展到整个东北亚地区\n- **合作伙伴**：新增 5 家品牌赞助商\n\n### 活动内容\n\n1. **游戏作品展示** — 12+ 款独立游戏现场试玩\n2. **开发者分享** — 5 场主题演讲与圆桌讨论\n3. **商务对接** — 发行商与开发者一对一洽谈\n4. **高校联盟论坛** — 12 所高校代表交流合作\n5. **颁奖典礼** — 年度最佳独立游戏评选\n\n### 参展作品（部分）\n\n- 🎮 《末日旅人》— 末日废土生存冒险\n- 🎮 《幻刃录》— 赛博国风动作 RPG\n- 🎮 《星之庭院》— 治愈放置模拟经营\n- 🎮 《虚空棋局》— 硬核策略战棋\n- 🎮 《重力反转》— 创新平台解谜\n- 🎮 《冰原故事》— 东北工业美学叙事冒险\n\n## 报名信息\n\n**活动时间**：2026年3月15日 10:00 - 18:00  \n**活动地点**：沈阳（具体场地待公布）  \n**报名方式**：关注微信公众号「冻土回声」获取报名链接\n\n## 合作伙伴\n\n感谢以下合作伙伴对 SSCA 2026 的支持：\n\n- 傲风 AutoFull — 官方电竞椅合作伙伴\n- 华硕 ASUS — 硬件支持\n- 奕威 EVNIA — 显示器赞助\n- 哔哩哔哩 — 直播平台合作伙伴\n\n---\n\n*期待在 SSCA 2026 与您相见！*\n"
    }
  ]
};

export const articleSlugs: Record<string, string[]> = {"en":["game-jam-2026-review","ssca-2026-announcement"],"zh":["game-jam-2026-review","ssca-2026-announcement"]};

export function getArticles(locale: string): ArticleMeta[] {
  return (articlesData[locale] || []).map(({ content, ...meta }) => meta);
}

export function getArticleBySlug(locale: string, slug: string): Article | null {
  return articlesData[locale]?.find((a) => a.slug === slug) || null;
}

export function getAllArticleSlugs(locale: string): string[] {
  return articleSlugs[locale] || [];
}
