import type { Locale } from '@/i18n/routing';

export interface GameInfo {
  id: string;
  title: string;
  titleEn: string;
  genre: string;
  status: 'demo' | 'pv' | 'released' | 'dev';
  statusLabel: string;
  description: string;
  category: string;
  steamUrl?: string;
  websiteUrl?: string;
}

export interface ActivityInfo {
  id: string;
  title: string;
  titleEn: string;
  date: string;
  location: string;
  description: string;
  status: 'upcoming' | 'completed';
  highlight?: boolean;
  /** 活动照片路径，相对于 public/ 目录，如 /images/activities/ssca-2026-01.jpg */
  images?: string[];
}

export interface UniversityInfo {
  id: string;
  name: string;
  nameEn: string;
  location: string;
}

export interface PartnerInfo {
  id: string;
  name: string;
  nameEn?: string;
  category: string;
  description: string;
  logo: string;
  website?: string;
}

export interface TimelineEvent {
  year: string;
  title: string;
  description: string;
}

export interface RoadmapPhase {
  phase: string;
  title: string;
  items: string[];
  status: 'completed' | 'in-progress' | 'planned';
}

// ============ 多语言数据 ============

type LocalizedData = {
  games: GameInfo[];
  activities: ActivityInfo[];
  universities: UniversityInfo[];
  partners: PartnerInfo[];
  timelineEvents: TimelineEvent[];
  roadmapPhases: RoadmapPhase[];
};

const zhData: LocalizedData = {
  games: [
    {
      id: 'doomsday-traveler',
      title: '末日旅人',
      titleEn: 'Doomsday Traveler',
      genre: '末日废土 · 生存冒险',
      status: 'demo',
      statusLabel: 'Demo',
      description: '在末日废土中探索生存，融合赛博朋克视觉风格与中国传统文化元素，打造独特的末世体验。',
      category: '末日废土与赛博国风',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'phantom-blade',
      title: '幻刃录',
      titleEn: 'Phantom Blade Chronicles',
      genre: '赛博国风 · 动作RPG',
      status: 'pv',
      statusLabel: 'PV',
      description: '赛博朋克都市与中国武侠碰撞，快节奏战斗系统配合深度剧情叙事。',
      category: '末日废土与赛博国风',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'neon-dynasty',
      title: '霓虹王朝',
      titleEn: 'Neon Dynasty',
      genre: '赛博国风 · 策略卡牌',
      status: 'dev',
      statusLabel: '开发中',
      description: '融合中国传统水墨画风与赛博朋克美学的策略卡牌游戏，在霓虹闪烁的古都中运筹帷幄。',
      category: '末日废土与赛博国风',
    },
    {
      id: 'star-garden',
      title: '星之庭院',
      titleEn: 'Star Garden',
      genre: '治愈放置 · 模拟经营',
      status: 'demo',
      statusLabel: 'Demo',
      description: '在星空下打造属于你的治愈庭院，种植奇花异草，与可爱的星灵一起度过悠闲时光。',
      category: '治愈放置与硬核智斗',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'void-chess',
      title: '虚空棋局',
      titleEn: 'Void Chess',
      genre: '硬核智斗 · 策略战棋',
      status: 'released',
      statusLabel: '已发布',
      description: '在虚空棋盘上与对手展开智力对决，独创的规则体系带来无限策略可能性。',
      category: '治愈放置与硬核智斗',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'echo-of-silence',
      title: '寂静回声',
      titleEn: 'Echo of Silence',
      genre: '治愈放置 · 音乐节奏',
      status: 'pv',
      statusLabel: 'PV',
      description: '在寂静中聆听回声，用音乐治愈心灵。独特的放置玩法与原创音乐结合。',
      category: '治愈放置与硬核智斗',
    },
    {
      id: 'gravity-shift',
      title: '重力反转',
      titleEn: 'Gravity Shift',
      genre: '创新玩法 · 平台解谜',
      status: 'demo',
      statusLabel: 'Demo',
      description: '颠覆传统平台跳跃，自由操控重力方向，在颠倒的世界中寻找出路。',
      category: '脑洞大开的创新玩法',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'time-weaver',
      title: '时间织者',
      titleEn: 'Time Weaver',
      genre: '创新玩法 · 时间操控',
      status: 'dev',
      statusLabel: '开发中',
      description: '操控时间线改变战局，每一次选择都会产生蝴蝶效应，编织属于你的命运。',
      category: '脑洞大开的创新玩法',
    },
    {
      id: 'ink-soul',
      title: '墨魂',
      titleEn: 'Ink Soul',
      genre: '创新玩法 · 水墨动作',
      status: 'pv',
      statusLabel: 'PV',
      description: '水墨画风搭配创意动作系统，在画卷般的世界中书写你的武侠传奇。',
      category: '脑洞大开的创新玩法',
    },
    {
      id: 'frost-punk-tales',
      title: '冰原故事',
      titleEn: 'Frost Punk Tales',
      genre: '末日废土 · 叙事冒险',
      status: 'released',
      statusLabel: '已发布',
      description: '在冰封的废土上展开一段温暖人心的冒险旅程，东北工业美学与末日叙事的碰撞。',
      category: '末日废土与赛博国风',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'cipher-war',
      title: '密码战争',
      titleEn: 'Cipher War',
      genre: '硬核智斗 · 解谜',
      status: 'demo',
      statusLabel: 'Demo',
      description: '破解层层密码，在数字与逻辑的迷宫中寻找真相。烧脑解谜与精彩剧情并行。',
      category: '治愈放置与硬核智斗',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'dream-link',
      title: '梦境链接',
      titleEn: 'Dream Link',
      genre: '创新玩法 · 多人协作',
      status: 'dev',
      statusLabel: '开发中',
      description: '进入他人的梦境，通过独特的链接机制合作解谜，探索潜意识的无尽可能。',
      category: '脑洞大开的创新玩法',
    },
  ],
  activities: [
    {
      id: 'ssca-2026',
      title: 'SSCA 动漫游戏博览会 · 游戏区',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2026-03-15',
      location: '沈阳',
      description: '冻土回声在 SSCA 沈阳动漫游戏博览会上承办独立游戏专区，为东北地区的独立游戏开发者提供展示和交流的平台，吸引超过500名开发者和玩家参与。',
      status: 'completed',
      images: [
        '/images/activities/ssca-2026-01.jpg',
        '/images/activities/ssca-2026-02.jpg',
        '/images/activities/ssca-2026-03.jpg',
      ],
    },
    {
      id: 'ggj-2026',
      title: 'Global Game Jam 2026 沈阳站',
      titleEn: 'Global Game Jam 2026 Shenyang Site',
      date: '2026-02',
      location: '沈阳（线上+线下）',
      description: '全球最大的游戏创作马拉松活动落地沈阳，48小时内从零开始创作游戏原型，汇聚东北亚地区最具创意的游戏开发者。',
      status: 'completed',
      images: [
        '/images/activities/ggj-2026-01.jpg',
        '/images/activities/ggj-2026-02.jpg',
        '/images/activities/ggj-2026-03.jpg',
      ],
    },
    {
      id: 'northern-anime-carnival-2026-05',
      title: '北境动漫游戏嘉年华',
      titleEn: 'Northern Anime & Game Carnival',
      date: '2026-05',
      location: '沈阳',
      description: '冻土回声携12款东北亚独立游戏作品亮相北境动漫游戏嘉年华，展示区域游戏创作力量，拓展全国合作网络。',
      status: 'completed',
      images: [
        '/images/activities/northern-anime-carnival-2026-05-01.jpg',
        '/images/activities/northern-anime-carnival-2026-05-02.jpg',
      ],
    },
    {
      id: 'ciga-gamejam-2026-shenyang',
      title: '2026 CiGA Game Jam 沈阳站',
      titleEn: '2026 CiGA Game Jam · Shenyang Site',
      date: '2026-07',
      location: '沈阳',
      description: '中国独立游戏联盟（CiGA）年度Game Jam落地沈阳，48小时限时创作，汇聚东北地区最具创意的游戏开发力量。',
      status: 'completed',
      images: [
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-01.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-02.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-03.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-04.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-05.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-06.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-07.webp',
      ],
    },
    {
      id: 'northern-anime-2026',
      title: '北境动漫游戏嘉年华 · 游戏区',
      titleEn: 'Northern Anime & Game Carnival · Game Zone',
      date: '2026-10',
      location: '沈阳',
      description: '北境动漫游戏嘉年华独立游戏专区，冻土回声联合承办，为东北亚独立游戏开发者提供展示与交流平台。',
      status: 'upcoming',
      highlight: true,
    },
    {
      id: 'ssca-2027',
      title: 'SSCA 动漫游戏博览会 · 游戏区',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2027-03',
      location: '沈阳',
      description: '冻土回声在 SSCA 沈阳动漫游戏博览会上承办独立游戏专区，为东北地区的独立游戏开发者提供展示和交流的平台。',
      status: 'upcoming',
    },
    {
      id: 'ggj-2027',
      title: 'Global Game Jam 2027 沈阳站',
      titleEn: 'Global Game Jam 2027 Shenyang Site',
      date: '2027-02',
      location: '沈阳',
      description: '全球最大的游戏创作马拉松活动再度落地沈阳，48小时内从零开始创作游戏原型，汇聚东北亚最具创意的游戏开发者。',
      status: 'upcoming',
    },
  ],
  universities: [
    { id: 'neu', name: '东北大学', nameEn: 'Northeastern University', location: '沈阳' },
    { id: 'lnu', name: '辽宁大学', nameEn: 'Liaoning University', location: '沈阳' },
    { id: 'dlut', name: '大连理工大学', nameEn: 'Dalian University of Technology', location: '大连' },
    { id: 'dlu', name: '大连大学', nameEn: 'Dalian University', location: '大连' },
    { id: 'jlu', name: '吉林大学', nameEn: 'Jilin University', location: '长春' },
    { id: 'nenu', name: '东北师范大学', nameEn: 'Northeast Normal University', location: '长春' },
    { id: 'hit', name: '哈尔滨工业大学', nameEn: 'Harbin Institute of Technology', location: '哈尔滨' },
    { id: 'hrbeu', name: '哈尔滨工程大学', nameEn: 'Harbin Engineering University', location: '哈尔滨' },
    { id: 'imu', name: '内蒙古大学', nameEn: 'Inner Mongolia University', location: '呼和浩特' },
    { id: 'syau', name: '沈阳农业大学', nameEn: 'Shenyang Agricultural University', location: '沈阳' },
    { id: 'sut', name: '沈阳工业大学', nameEn: 'Shenyang University of Technology', location: '沈阳' },
    { id: 'dufe', name: '东北财经大学', nameEn: 'Dongbei University of Finance and Economics', location: '大连' },
  ],
  partners: [
    {
      id: 'unity-china',
      name: 'Unity 中国',
      nameEn: 'Unity China',
      category: '引擎技术',
      description: '全球领先的实时 3D 内容创作平台，为独立游戏开发者提供强大的技术支持与生态资源。',
      logo: '/images/partners/unity.svg',
    },
    {
      id: 'netease-digital',
      name: '网易沈阳数字产业中心',
      nameEn: 'Netease Shenyang Digital Industry Center',
      category: '产业孵化',
      description: '网易在东北地区设立的数字产业创新基地，聚焦游戏、数字内容与科技产业孵化。',
      logo: '/images/partners/netease-digital.svg',
    },
    {
      id: 'netease-edu',
      name: '网易游戏学堂',
      nameEn: 'Netease Game Academy',
      category: '教育培养',
      description: '网易游戏旗下的游戏人才培养平台，提供游戏设计、开发、美术等专业课程与培训。',
      logo: '/images/partners/netease-edu.svg',
    },
    {
      id: 'tencent-edu',
      name: '腾讯游戏学堂',
      nameEn: 'Tencent Game Academy',
      category: '教育培养',
      description: '腾讯游戏旗下的游戏人才培养与学术交流平台，致力于推动游戏产业人才发展。',
      logo: '/images/partners/tencent-edu.svg',
    },
    {
      id: 'asus-liaoning',
      name: '华硕辽宁',
      nameEn: 'ASUS Liaoning',
      category: '硬件设备',
      description: '华硕在辽宁地区的分支机构，为游戏活动与开发者提供高性能硬件设备支持。',
      logo: '/images/partners/asus.svg',
    },
    {
      id: 'aura',
      name: '狼蛛 Aura',
      nameEn: 'Aura',
      category: '外设装备',
      description: '知名电竞外设品牌，为独立游戏开发者和玩家提供专业级外设装备。',
      logo: '/images/partners/aura.svg',
    },
  ],
  timelineEvents: [
    {
      year: '2024',
      title: '品牌创立',
      description: '冻土回声（Permafrost Echo）品牌在沈阳正式成立，定位为东北亚独立游戏生态平台。',
    },
    {
      year: '2025.03',
      title: '首届 SSCA 动漫游戏博览会 · 游戏区',
      description: '首次承办 SSCA 沈阳动漫游戏博览会的独立游戏专区，吸引 200+ 参与者。',
    },
    {
      year: '2025.08',
      title: '高校联盟启动',
      description: '联合东北地区12所高校成立独立游戏高校联盟，建立校园开发者网络。',
    },
    {
      year: '2026.02',
      title: 'GGJ 2026 沈阳站',
      description: '首次承办 Global Game Jam 沈阳站点，48小时创作马拉松圆满成功。',
    },
    {
      year: '2026.03',
      title: 'SSCA 2026 动漫游戏博览会 · 游戏区',
      description: 'SSCA 2026 规模升级，冻土回声游戏专区参展作品增至 12 款，参与者突破 500 人。',
    },
    {
      year: '2026.05',
      title: '北境动漫游戏嘉年华',
      description: '携12款作品亮相北境动漫游戏嘉年华，拓展全国影响力。',
    },
  ],
  roadmapPhases: [
    {
      phase: 'Phase 1',
      title: '品牌建立与社群运营',
      items: [
        '建立冻土回声品牌视觉体系',
        '搭建微信社群与QQ社群（600+人）',
        '联合东北12所高校成立联盟',
        '承办首届SSCA动漫游戏博览会游戏专区',
      ],
      status: 'completed',
    },
    {
      phase: 'Phase 2',
      title: '活动体系化与内容产出',
      items: [
        '建立Game Jam常态化机制（每年2届）',
        '启动独立游戏作品孵化计划',
        '产出深度访谈与行业分析内容',
        '拓展合作伙伴网络（9+品牌）',
      ],
      status: 'in-progress',
    },
    {
      phase: 'Phase 3',
      title: '区域影响力扩展',
      items: [
        '覆盖东北亚19+高校联盟',
        '举办首届冻土回声独立游戏展',
        '建立开发者社区平台（论坛/Wiki）',
        '启动跨区域合作项目（日韩俄）',
      ],
      status: 'planned',
    },
    {
      phase: 'Phase 4',
      title: '生态平台建设',
      items: [
        '搭建独立游戏发行平台',
        '设立独立游戏开发者基金',
        '举办国际级独立游戏节',
        '打造东北亚最大独立游戏生态网络',
      ],
      status: 'planned',
    },
  ],
};

const enData: LocalizedData = {
  games: [
    {
      id: 'doomsday-traveler',
      title: 'Doomsday Traveler',
      titleEn: 'Doomsday Traveler',
      genre: 'Post-Apocalyptic · Survival Adventure',
      status: 'demo',
      statusLabel: 'Demo',
      description: 'Explore and survive in a post-apocalyptic wasteland, blending cyberpunk visual style with traditional Chinese cultural elements to create a unique end-of-world experience.',
      category: 'Post-Apocalyptic & Cyber-Chinese',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'phantom-blade',
      title: 'Phantom Blade Chronicles',
      titleEn: 'Phantom Blade Chronicles',
      genre: 'Cyber-Chinese · Action RPG',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Cyberpunk city meets Chinese martial arts, with fast-paced combat and deep narrative storytelling.',
      category: 'Post-Apocalyptic & Cyber-Chinese',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'neon-dynasty',
      title: 'Neon Dynasty',
      titleEn: 'Neon Dynasty',
      genre: 'Cyber-Chinese · Strategy Card',
      status: 'dev',
      statusLabel: 'In Development',
      description: 'A strategy card game blending traditional Chinese ink wash art with cyberpunk aesthetics. Plot your moves in a neon-lit ancient capital.',
      category: 'Post-Apocalyptic & Cyber-Chinese',
    },
    {
      id: 'star-garden',
      title: 'Star Garden',
      titleEn: 'Star Garden',
      genre: 'Healing Idle · Simulation',
      status: 'demo',
      statusLabel: 'Demo',
      description: 'Create your own healing garden under the stars, grow exotic plants, and spend leisurely time with adorable star spirits.',
      category: 'Healing Idle & Hardcore Strategy',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'void-chess',
      title: 'Void Chess',
      titleEn: 'Void Chess',
      genre: 'Hardcore Strategy · Tactical Chess',
      status: 'released',
      statusLabel: 'Released',
      description: 'Engage in intellectual duels on a void chessboard. An original rule system offers infinite strategic possibilities.',
      category: 'Healing Idle & Hardcore Strategy',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'echo-of-silence',
      title: 'Echo of Silence',
      titleEn: 'Echo of Silence',
      genre: 'Healing Idle · Music Rhythm',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Listen to echoes in silence, heal your soul with music. A unique idle gameplay experience combined with original music.',
      category: 'Healing Idle & Hardcore Strategy',
    },
    {
      id: 'gravity-shift',
      title: 'Gravity Shift',
      titleEn: 'Gravity Shift',
      genre: 'Innovative Gameplay · Puzzle Platformer',
      status: 'demo',
      statusLabel: 'Demo',
      description: 'Subvert traditional platform jumping by freely controlling gravity direction. Find your way out in an upside-down world.',
      category: 'Innovative Gameplay',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'time-weaver',
      title: 'Time Weaver',
      titleEn: 'Time Weaver',
      genre: 'Innovative Gameplay · Time Manipulation',
      status: 'dev',
      statusLabel: 'In Development',
      description: 'Manipulate the timeline to change the course of battle. Every choice creates a butterfly effect, weaving your own destiny.',
      category: 'Innovative Gameplay',
    },
    {
      id: 'ink-soul',
      title: 'Ink Soul',
      titleEn: 'Ink Soul',
      genre: 'Innovative Gameplay · Ink-Wash Action',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Ink-wash art style paired with a creative action system. Write your martial arts legend in a world that looks like a living painting.',
      category: 'Innovative Gameplay',
    },
    {
      id: 'frost-punk-tales',
      title: 'Frost Punk Tales',
      titleEn: 'Frost Punk Tales',
      genre: 'Post-Apocalyptic · Narrative Adventure',
      status: 'released',
      statusLabel: 'Released',
      description: 'Embark on a heartwarming adventure across a frozen wasteland. A collision of Northeast China industrial aesthetics and post-apocalyptic narrative.',
      category: 'Post-Apocalyptic & Cyber-Chinese',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'cipher-war',
      title: 'Cipher War',
      titleEn: 'Cipher War',
      genre: 'Hardcore Strategy · Puzzle',
      status: 'demo',
      statusLabel: 'Demo',
      description: 'Crack layers of codes and find the truth in a maze of numbers and logic. Brain-burning puzzles paired with compelling storytelling.',
      category: 'Healing Idle & Hardcore Strategy',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'dream-link',
      title: 'Dream Link',
      titleEn: 'Dream Link',
      genre: 'Innovative Gameplay · Co-op',
      status: 'dev',
      statusLabel: 'In Development',
      description: 'Enter the dreams of others and solve puzzles together through a unique linking mechanic. Explore the infinite possibilities of the subconscious.',
      category: 'Innovative Gameplay',
    },
  ],
  activities: [
    {
      id: 'ssca-2026',
      title: 'SSCA Animation, Comic & Game Expo · Game Zone',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2026-03-15',
      location: 'Shenyang',
      description: 'Permafrost Echo hosts the indie game zone at the SSCA Shenyang Animation, Comic & Game Expo, providing a showcase platform for indie developers from Northeast China, attracting over 500 developers and players.',
      status: 'completed',
      images: [
        '/images/activities/ssca-2026-01.jpg',
        '/images/activities/ssca-2026-02.jpg',
        '/images/activities/ssca-2026-03.jpg',
      ],
    },
    {
      id: 'ggj-2026',
      title: 'Global Game Jam 2026 · Shenyang Site',
      titleEn: 'Global Game Jam 2026 · Shenyang Site',
      date: '2026-02',
      location: 'Shenyang (Online + Offline)',
      description: "The world's largest game creation jam lands in Shenyang. Create game prototypes from scratch in 48 hours, bringing together Northeast Asia's most creative developers.",
      status: 'completed',
      images: [
        '/images/activities/ggj-2026-01.jpg',
        '/images/activities/ggj-2026-02.jpg',
        '/images/activities/ggj-2026-03.jpg',
      ],
    },
    {
      id: 'beijing-expo-2026',
      title: 'Beijing Indie Game Expo 2026',
      titleEn: 'Beijing Indie Game Expo 2026',
      date: '2026-05',
      location: 'Beijing',
      description: 'Permafrost Echo brings 12 Northeast Asia indie game titles to the Beijing Indie Game Expo, showcasing regional creative power and expanding national cooperation networks.',
      status: 'completed',
      images: [
        '/images/activities/beijing-expo-2026-01.jpg',
        '/images/activities/beijing-expo-2026-02.jpg',
      ],
    },
    {
      id: 'ciga-gamejam-2026-shenyang',
      title: '2026 CiGA Game Jam · Shenyang Site',
      titleEn: '2026 CiGA Game Jam · Shenyang Site',
      date: '2026-07',
      location: 'Shenyang',
      description: 'The annual CiGA (China Indie Game Alliance) Game Jam lands in Shenyang. A 48-hour creation sprint bringing together the most creative game developers from Northeast China.',
      status: 'completed',
      images: [
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-01.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-02.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-03.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-04.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-05.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-06.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-07.webp',
      ],
    },
    {
      id: 'northern-anime-2026',
      title: 'Northern Anime & Game Carnival · Game Zone',
      titleEn: 'Northern Anime & Game Carnival · Game Zone',
      date: '2026-10',
      location: 'Shenyang',
      description: 'The indie game zone of the Northern Anime & Game Carnival, co-organized by Permafrost Echo, providing a showcase and networking platform for Northeast Asia indie game developers.',
      status: 'upcoming',
      highlight: true,
    },
    {
      id: 'ssca-2027',
      title: 'SSCA Animation, Comic & Game Expo · Game Zone',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2027-03',
      location: 'Shenyang',
      description: 'Permafrost Echo hosts the indie game zone at the SSCA Shenyang Animation, Comic & Game Expo, providing a showcase platform for indie developers from Northeast China.',
      status: 'upcoming',
    },
    {
      id: 'ggj-2027',
      title: 'Global Game Jam 2027 · Shenyang Site',
      titleEn: 'Global Game Jam 2027 · Shenyang Site',
      date: '2027-02',
      location: 'Shenyang',
      description: "The world's largest game creation jam returns to Shenyang. Create game prototypes from scratch in 48 hours with Northeast Asia's most creative developers.",
      status: 'upcoming',
    },
  ],
  universities: [
    { id: 'neu', name: 'Northeastern University', nameEn: 'Northeastern University', location: 'Shenyang' },
    { id: 'lnu', name: 'Liaoning University', nameEn: 'Liaoning University', location: 'Shenyang' },
    { id: 'dlut', name: 'Dalian University of Technology', nameEn: 'Dalian University of Technology', location: 'Dalian' },
    { id: 'dlu', name: 'Dalian University', nameEn: 'Dalian University', location: 'Dalian' },
    { id: 'jlu', name: 'Jilin University', nameEn: 'Jilin University', location: 'Changchun' },
    { id: 'nenu', name: 'Northeast Normal University', nameEn: 'Northeast Normal University', location: 'Changchun' },
    { id: 'hit', name: 'Harbin Institute of Technology', nameEn: 'Harbin Institute of Technology', location: 'Harbin' },
    { id: 'hrbeu', name: 'Harbin Engineering University', nameEn: 'Harbin Engineering University', location: 'Harbin' },
    { id: 'imu', name: 'Inner Mongolia University', nameEn: 'Inner Mongolia University', location: 'Hohhot' },
    { id: 'syau', name: 'Shenyang Agricultural University', nameEn: 'Shenyang Agricultural University', location: 'Shenyang' },
    { id: 'sut', name: 'Shenyang University of Technology', nameEn: 'Shenyang University of Technology', location: 'Shenyang' },
    { id: 'dufe', name: 'Dongbei University of Finance and Economics', nameEn: 'Dongbei University of Finance and Economics', location: 'Dalian' },
  ],
  partners: [
    {
      id: 'unity-china',
      name: 'Unity China',
      nameEn: 'Unity China',
      category: 'Engine Technology',
      description: "The world's leading real-time 3D content creation platform, providing powerful technical support and ecosystem resources for indie game developers.",
      logo: '/images/partners/unity.svg',
    },
    {
      id: 'netease-digital',
      name: 'Netease Shenyang Digital Industry Center',
      nameEn: 'Netease Shenyang Digital Industry Center',
      category: 'Industry Incubation',
      description: "Netease's digital industry innovation base in Northeast China, focusing on game, digital content, and tech industry incubation.",
      logo: '/images/partners/netease-digital.svg',
    },
    {
      id: 'netease-edu',
      name: 'Netease Game Academy',
      nameEn: 'Netease Game Academy',
      category: 'Education & Training',
      description: "Netease Games' talent cultivation platform, offering professional courses and training in game design, development, and art.",
      logo: '/images/partners/netease-edu.svg',
    },
    {
      id: 'tencent-edu',
      name: 'Tencent Game Academy',
      nameEn: 'Tencent Game Academy',
      category: 'Education & Training',
      description: "Tencent Games' talent cultivation and academic exchange platform, dedicated to advancing game industry talent development.",
      logo: '/images/partners/tencent-edu.svg',
    },
    {
      id: 'asus-liaoning',
      name: 'ASUS Liaoning',
      nameEn: 'ASUS Liaoning',
      category: 'Hardware',
      description: "ASUS's regional branch in Liaoning, providing high-performance hardware support for game events and developers.",
      logo: '/images/partners/asus.svg',
    },
    {
      id: 'aura',
      name: 'Aura',
      nameEn: 'Aura',
      category: 'Gaming Peripherals',
      description: 'A renowned esports peripherals brand, providing professional-grade gear for indie game developers and players.',
      logo: '/images/partners/aura.svg',
    },
  ],
  timelineEvents: [
    {
      year: '2024',
      title: 'Brand Founding',
      description: 'Permafrost Echo brand officially established in Shenyang, positioned as a Northeast Asia indie game ecosystem platform.',
    },
    {
      year: '2025.03',
      title: '1st SSCA Expo · Game Zone',
      description: 'Hosted the indie game zone at the first SSCA Shenyang Animation, Comic & Game Expo, attracting 200+ participants.',
    },
    {
      year: '2025.08',
      title: 'University Alliance Launch',
      description: 'Established an indie game university alliance with 12 universities across Northeast China, building a campus developer network.',
    },
    {
      year: '2026.02',
      title: 'GGJ 2026 Shenyang Site',
      description: 'First time hosting the Global Game Jam Shenyang site. The 48-hour creation marathon was a resounding success.',
    },
    {
      year: '2026.03',
      title: 'SSCA 2026 Expo · Game Zone',
      description: 'SSCA 2026 scaled up with 12 exhibited titles and over 500 participants at the game zone.',
    },
    {
      year: '2026.05',
      title: 'Beijing Expo Debut',
      description: 'Debuted at the Beijing Indie Game Expo with 12 titles, expanding national influence.',
    },
  ],
  roadmapPhases: [
    {
      phase: 'Phase 1',
      title: 'Brand Building & Community Operations',
      items: [
        'Establish Permafrost Echo brand visual identity',
        'Build WeChat & QQ communities (600+ members)',
        'Form alliance with 12 Northeast China universities',
        'Host the first SSCA Animation, Comic & Game Expo game zone',
      ],
      status: 'completed',
    },
    {
      phase: 'Phase 2',
      title: 'Event Systematization & Content Production',
      items: [
        'Establish regular Game Jam schedule (2 per year)',
        'Launch indie game incubation program',
        'Produce in-depth interviews and industry analysis',
        'Expand partner network (9+ brands)',
      ],
      status: 'in-progress',
    },
    {
      phase: 'Phase 3',
      title: 'Regional Influence Expansion',
      items: [
        'Cover 19+ university alliances across Northeast Asia',
        'Hold the first Permafrost Echo Indie Game Expo',
        'Build developer community platform (Forum/Wiki)',
        'Launch cross-regional cooperation projects (Japan, Korea, Russia)',
      ],
      status: 'planned',
    },
    {
      phase: 'Phase 4',
      title: 'Ecosystem Platform Construction',
      items: [
        'Build indie game publishing platform',
        'Establish indie game developer fund',
        'Host international indie game festival',
        'Build the largest indie game ecosystem network in Northeast Asia',
      ],
      status: 'planned',
    },
  ],
};

const jaData: LocalizedData = {
  games: [
    {
      id: 'doomsday-traveler',
      title: 'ドゥームズデイ・トラベラー',
      titleEn: 'Doomsday Traveler',
      genre: '終末廃土 · サバイバルアドベンチャー',
      status: 'demo',
      statusLabel: 'デモ',
      description: '終末の廃土を探索し生き延びろ。サイバーパンクのビジュアルスタイルと中国伝統文化要素を融合させた、ユニークな終末体験。',
      category: '終末廃土 & サイバー中華',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'phantom-blade',
      title: 'ファントムブレード・クロニクル',
      titleEn: 'Phantom Blade Chronicles',
      genre: 'サイバー中華 · アクションRPG',
      status: 'pv',
      statusLabel: 'PV',
      description: 'サイバーパンク都市と中国武術の衝突。高速戦闘システムと深い物語が融合。',
      category: '終末廃土 & サイバー中華',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'neon-dynasty',
      title: 'ネオンダイナスティ',
      titleEn: 'Neon Dynasty',
      genre: 'サイバー中華 · 戦略カード',
      status: 'dev',
      statusLabel: '開発中',
      description: '中国伝統の水墨画風とサイバーパンク美学を融合させた戦略カードゲーム。ネオン輝く古都で戦略を巡らせろ。',
      category: '終末廃土 & サイバー中華',
    },
    {
      id: 'star-garden',
      title: 'スターガーデン',
      titleEn: 'Star Garden',
      genre: '癒し放置 · 経営シミュレーション',
      status: 'demo',
      statusLabel: 'デモ',
      description: '星空の下であなただけの癒しの庭を作り、珍しい花を育て、かわいい星の精霊とのんびり過ごそう。',
      category: '癒し放置 & ハードコア戦略',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'void-chess',
      title: 'ヴォイドチェス',
      titleEn: 'Void Chess',
      genre: 'ハードコア戦略 · タクティカルチェス',
      status: 'released',
      statusLabel: 'リリース済',
      description: '虚空のチェス盤で相手と知的対決。独自のルール体系が無限の戦略可能性をもたらす。',
      category: '癒し放置 & ハードコア戦略',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'echo-of-silence',
      title: 'サイレンス・エコー',
      titleEn: 'Echo of Silence',
      genre: '癒し放置 · 音楽リズム',
      status: 'pv',
      statusLabel: 'PV',
      description: '静寂の中でこだまを聴き、音楽で心を癒す。独自の放置プレイとオリジナル音楽の融合。',
      category: '癒し放置 & ハードコア戦略',
    },
    {
      id: 'gravity-shift',
      title: 'グラビティシフト',
      titleEn: 'Gravity Shift',
      genre: '革新的ゲームプレイ · パズルプラットフォーマー',
      status: 'demo',
      statusLabel: 'デモ',
      description: '重力方向を自在に操り、従来のプラットフォームジャンプを覆す。逆さまの世界で出口を探せ。',
      category: '革新的ゲームプレイ',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'time-weaver',
      title: 'タイムウィーバー',
      titleEn: 'Time Weaver',
      genre: '革新的ゲームプレイ · 時間操作',
      status: 'dev',
      statusLabel: '開発中',
      description: '時間軸を操作して戦局を変えろ。すべての選択がバタフライ効果を生み、あなただけの運命を紡ぐ。',
      category: '革新的ゲームプレイ',
    },
    {
      id: 'ink-soul',
      title: '墨魂（ボクコン）',
      titleEn: 'Ink Soul',
      genre: '革新的ゲームプレイ · 水墨アクション',
      status: 'pv',
      statusLabel: 'PV',
      description: '水墨画風と創造的なアクションシステムの融合。絵巻物のような世界で武侠伝説を綴れ。',
      category: '革新的ゲームプレイ',
    },
    {
      id: 'frost-punk-tales',
      title: 'フロストパンク・テイルズ',
      titleEn: 'Frost Punk Tales',
      genre: '終末廃土 · ナラティブアドベンチャー',
      status: 'released',
      statusLabel: 'リリース済',
      description: '氷に閉ざされた廃土で心温まる冒険の旅へ。東北工業美学と終末ナラティブの衝突。',
      category: '終末廃土 & サイバー中華',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'cipher-war',
      title: 'サイファーウォー',
      titleEn: 'Cipher War',
      genre: 'ハードコア戦略 · パズル',
      status: 'demo',
      statusLabel: 'デモ',
      description: '暗号の層を解き明かし、数字と論理の迷宮で真実を見つけ出せ。頭脳を焼くパズルと魅力的なストーリーが並走する。',
      category: '癒し放置 & ハードコア戦略',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'dream-link',
      title: 'ドリームリンク',
      titleEn: 'Dream Link',
      genre: '革新的ゲームプレイ · 協力プレイ',
      status: 'dev',
      statusLabel: '開発中',
      description: '他人の夢に入り込み、独自のリンクメカニズムで協力して謎を解け。潜在意識の無限の可能性を探求しよう。',
      category: '革新的ゲームプレイ',
    },
  ],
  activities: [
    {
      id: 'ssca-2026',
      title: 'SSCA アニメ・コミック・ゲーム博覧会 · ゲームゾーン',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2026-03-15',
      location: '瀋陽',
      description: 'パーマフロスト・エコーがSSCA瀋陽アニメ・コミック・ゲーム博覧会でインディーゲームゾーンを運営。東北地方のインディーゲーム開発者に展示・交流のプラットフォームを提供し、500名以上の開発者とプレイヤーが参加。',
      status: 'completed',
      images: [
        '/images/activities/ssca-2026-01.jpg',
        '/images/activities/ssca-2026-02.jpg',
        '/images/activities/ssca-2026-03.jpg',
      ],
    },
    {
      id: 'ggj-2026',
      title: 'Global Game Jam 2026 · 瀋陽会場',
      titleEn: 'Global Game Jam 2026 · Shenyang Site',
      date: '2026-02',
      location: '瀋陽（オンライン＋オフライン）',
      description: '世界最大のゲームクリエイションマラソンが瀋陽に上陸。48時間でゼロからゲームプロトタイプを制作し、東北アジアの最も創造的な開発者が集結。',
      status: 'completed',
      images: [
        '/images/activities/ggj-2026-01.jpg',
        '/images/activities/ggj-2026-02.jpg',
        '/images/activities/ggj-2026-03.jpg',
      ],
    },
    {
      id: 'northern-anime-carnival-2026-05',
      title: '北境アニメ・ゲームカーニバル',
      titleEn: 'Northern Anime & Game Carnival',
      date: '2026-05',
      location: '瀋陽',
      description: 'パーマフロスト・エコーが東北アジアのインディーゲーム12作品を携えて北境アニメ・ゲームカーニバルに出展。地域の創作力を示し、全国的な協力ネットワークを拡大。',
      status: 'completed',
      images: [
        '/images/activities/northern-anime-carnival-2026-05-01.jpg',
        '/images/activities/northern-anime-carnival-2026-05-02.jpg',
      ],
    },
    {
      id: 'ciga-gamejam-2026-shenyang',
      title: '2026 CiGA Game Jam · 瀋陽会場',
      titleEn: '2026 CiGA Game Jam · Shenyang Site',
      date: '2026-07',
      location: '瀋陽',
      description: 'CiGA（中国インディーゲーム連盟）の年次Game Jamが瀋陽に上陸。48時間の創作スプリントで、東北地域の最もクリエイティブなゲーム開発者が集結。',
      status: 'completed',
      images: [
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-01.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-02.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-03.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-04.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-05.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-06.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-07.webp',
      ],
    },
    {
      id: 'northern-anime-2026',
      title: '北境アニメゲームカーニバル · ゲームゾーン',
      titleEn: 'Northern Anime & Game Carnival · Game Zone',
      date: '2026-10',
      location: '瀋陽',
      description: '北境アニメゲームカーニバルのインディーゲーム専用ゾーン。パーマフロスト・エコーが共同運営し、東北アジアのインディーゲーム開発者に展示と交流の場を提供。',
      status: 'upcoming',
      highlight: true,
    },
    {
      id: 'ssca-2027',
      title: 'SSCA アニメ・コミック・ゲーム博覧会 · ゲームゾーン',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2027-03',
      location: '瀋陽',
      description: 'パーマフロスト・エコーがSSCA瀋陽アニメ・コミック・ゲーム博覧会でインディーゲームゾーンを運営。東北地方のインディーゲーム開発者に展示・交流のプラットフォームを提供。',
      status: 'upcoming',
    },
    {
      id: 'ggj-2027',
      title: 'Global Game Jam 2027 · 瀋陽会場',
      titleEn: 'Global Game Jam 2027 · Shenyang Site',
      date: '2027-02',
      location: '瀋陽',
      description: '世界最大のゲームクリエイションマラソンが再び瀋陽に。48時間でゼロからゲームプロトタイプを制作し、東北アジアの最も創造的な開発者と共に。',
      status: 'upcoming',
    },
  ],
  universities: [
    { id: 'neu', name: '東北大学', nameEn: 'Northeastern University', location: '瀋陽' },
    { id: 'lnu', name: '遼寧大学', nameEn: 'Liaoning University', location: '瀋陽' },
    { id: 'dlut', name: '大連理工大学', nameEn: 'Dalian University of Technology', location: '大連' },
    { id: 'dlu', name: '大連大学', nameEn: 'Dalian University', location: '大連' },
    { id: 'jlu', name: '吉林大学', nameEn: 'Jilin University', location: '長春' },
    { id: 'nenu', name: '東北師範大学', nameEn: 'Northeast Normal University', location: '長春' },
    { id: 'hit', name: 'ハルビン工業大学', nameEn: 'Harbin Institute of Technology', location: 'ハルビン' },
    { id: 'hrbeu', name: 'ハルビン工程大学', nameEn: 'Harbin Engineering University', location: 'ハルビン' },
    { id: 'imu', name: '内モンゴル大学', nameEn: 'Inner Mongolia University', location: 'フフホト' },
    { id: 'syau', name: '瀋陽農業大学', nameEn: 'Shenyang Agricultural University', location: '瀋陽' },
    { id: 'sut', name: '瀋陽工業大学', nameEn: 'Shenyang University of Technology', location: '瀋陽' },
    { id: 'dufe', name: '東北財経大学', nameEn: 'Dongbei University of Finance and Economics', location: '大連' },
  ],
  partners: [
    {
      id: 'unity-china',
      name: 'Unity 中国',
      nameEn: 'Unity China',
      category: 'エンジン技術',
      description: '世界をリードするリアルタイム3Dコンテンツ制作プラットフォーム。インディーゲーム開発者に強力な技術サポートとエコシステムリソースを提供。',
      logo: '/images/partners/unity.svg',
    },
    {
      id: 'netease-digital',
      name: 'NetEase瀋陽デジタル産業センター',
      nameEn: 'Netease Shenyang Digital Industry Center',
      category: '産業インキュベーション',
      description: 'NetEaseが東北地域に設立したデジタル産業イノベーション拠点。ゲーム、デジタルコンテンツ、テクノロジー産業のインキュベーションに注力。',
      logo: '/images/partners/netease-digital.svg',
    },
    {
      id: 'netease-edu',
      name: 'NetEaseゲームアカデミー',
      nameEn: 'Netease Game Academy',
      category: '教育育成',
      description: 'NetEase Games傘下のゲーム人材育成プラットフォーム。ゲームデザイン、開発、アートなどの専門コースとトレーニングを提供。',
      logo: '/images/partners/netease-edu.svg',
    },
    {
      id: 'tencent-edu',
      name: 'Tencentゲームアカデミー',
      nameEn: 'Tencent Game Academy',
      category: '教育育成',
      description: 'Tencent Games傘下のゲーム人材育成と学術交流プラットフォーム。ゲーム産業の人材発展を推進。',
      logo: '/images/partners/tencent-edu.svg',
    },
    {
      id: 'asus-liaoning',
      name: 'ASUS遼寧',
      nameEn: 'ASUS Liaoning',
      category: 'ハードウェア',
      description: 'ASUSの遼寧地域支社。ゲームイベントと開発者に高性能ハードウェアサポートを提供。',
      logo: '/images/partners/asus.svg',
    },
    {
      id: 'aura',
      name: 'Aura（オーラ）',
      nameEn: 'Aura',
      category: 'ゲーミングデバイス',
      description: '有名なeスポーツ周辺機器ブランド。インディーゲーム開発者とプレイヤーにプロフェッショナルグレードのデバイスを提供。',
      logo: '/images/partners/aura.svg',
    },
  ],
  timelineEvents: [
    {
      year: '2024',
      title: 'ブランド創立',
      description: 'パーマフロスト・エコー（Permafrost Echo）ブランドが瀋陽で正式に設立。東北アジアのインディーゲームエコシステムプラットフォームとして位置づけられる。',
    },
    {
      year: '2025.03',
      title: '第1回 SSCA 博覧会 · ゲームゾーン',
      description: '第1回SSCA瀋陽アニメ・コミック・ゲーム博覧会でインディーゲームゾーンを運営。200名以上が参加。',
    },
    {
      year: '2025.08',
      title: '大学連盟始動',
      description: '東北地域の12大学と連携し、インディーゲーム大学連盟を設立。キャンパス開発者ネットワークを構築。',
    },
    {
      year: '2026.02',
      title: 'GGJ 2026 瀋陽会場',
      description: 'Global Game Jam瀋陽会場を初開催。48時間の創作マラソンが大成功。',
    },
    {
      year: '2026.03',
      title: 'SSCA 2026 博覧会 · ゲームゾーン',
      description: 'SSCA 2026が規模拡大。出展作品が12作品に増え、参加者が500名を突破。',
    },
    {
      year: '2026.05',
      title: '北境アニメ・ゲームカーニバル',
      description: '12作品を携えて北境アニメ・ゲームカーニバルに初出展。全国的な影響力を拡大。',
    },
  ],
  roadmapPhases: [
    {
      phase: 'Phase 1',
      title: 'ブランド構築とコミュニティ運営',
      items: [
        'パーマフロスト・エコーのブランドビジュアル体系を確立',
        'WeChat・QQコミュニティを構築（600名以上）',
        '東北12大学と連盟を結成',
        '第1回SSCAアニメ・コミック・ゲーム博覧会ゲームゾーンを運営',
      ],
      status: 'completed',
    },
    {
      phase: 'Phase 2',
      title: 'イベント体系化とコンテンツ制作',
      items: [
        'Game Jam定期開催体制を確立（年2回）',
        'インディーゲーム作品インキュベーション計画を始動',
        '深層インタビューと業界分析コンテンツを制作',
        'パートナーネットワークを拡大（9ブランド以上）',
      ],
      status: 'in-progress',
    },
    {
      phase: 'Phase 3',
      title: '地域影響力の拡大',
      items: [
        '東北アジア19大学以上の連盟をカバー',
        '第1回パーマフロスト・エコーインディーゲーム展を開催',
        '開発者コミュニティプラットフォームを構築（フォーラム/Wiki）',
        '地域横断協力プロジェクトを始動（日韓露）',
      ],
      status: 'planned',
    },
    {
      phase: 'Phase 4',
      title: 'エコシステムプラットフォーム構築',
      items: [
        'インディーゲームパブリッシングプラットフォームを構築',
        'インディーゲーム開発者基金を設立',
        '国際級インディーゲームフェスティバルを開催',
        '東北アジア最大のインディーゲームエコシステムネットワークを構築',
      ],
      status: 'planned',
    },
  ],
};

const koData: LocalizedData = {
  games: [
    {
      id: 'doomsday-traveler',
      title: '둠스데이 트래블러',
      titleEn: 'Doomsday Traveler',
      genre: '포스트 아포칼립스 · 서바이벌 어드벤처',
      status: 'demo',
      statusLabel: '데모',
      description: '종말의 황무지에서 탐험하고 생존하라. 사이버펑크 비주얼 스타일과 중국 전통문화 요소를 융합한 독특한 종말 체험.',
      category: '포스트 아포칼립스 & 사이버 차이니즈',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'phantom-blade',
      title: '팬텀 블레이드 크로니클',
      titleEn: 'Phantom Blade Chronicles',
      genre: '사이버 차이니즈 · 액션 RPG',
      status: 'pv',
      statusLabel: 'PV',
      description: '사이버펑크 도시와 중국 무술의 충돌. 빠른 전투 시스템과 깊이 있는 내러티브가 결합.',
      category: '포스트 아포칼립스 & 사이버 차이니즈',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'neon-dynasty',
      title: '네온 다이너스티',
      titleEn: 'Neon Dynasty',
      genre: '사이버 차이니즈 · 전략 카드',
      status: 'dev',
      statusLabel: '개발 중',
      description: '중국 전통 수묵화 스타일과 사이버펑크 미학을 결합한 전략 카드 게임. 네온이 반짝이는 고대 수도에서 전략을 펼치세요.',
      category: '포스트 아포칼립스 & 사이버 차이니즈',
    },
    {
      id: 'star-garden',
      title: '스타 가든',
      titleEn: 'Star Garden',
      genre: '힐링 방치 · 경영 시뮬레이션',
      status: 'demo',
      statusLabel: '데모',
      description: '별빛 아래 당신만의 힐링 정원을 만들고, 신비로운 식물을 키우며, 사랑스러운 별의 정령들과 여유로운 시간을 보내세요.',
      category: '힐링 방치 & 하드코어 전략',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'void-chess',
      title: '보이드 체스',
      titleEn: 'Void Chess',
      genre: '하드코어 전략 · 택티컬 체스',
      status: 'released',
      statusLabel: '출시됨',
      description: '공허의 체스판에서 상대와 지적 대결을 펼치세요. 독창적인 규칙 체계가 무한한 전략적 가능성을 제공합니다.',
      category: '힐링 방치 & 하드코어 전략',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'echo-of-silence',
      title: '침묵의 메아리',
      titleEn: 'Echo of Silence',
      genre: '힐링 방치 · 음악 리듬',
      status: 'pv',
      statusLabel: 'PV',
      description: '고요 속에서 메아리를 듣고, 음악으로 마음을 치유하세요. 독특한 방치형 게임플레이와 오리지널 음악의 결합.',
      category: '힐링 방치 & 하드코어 전략',
    },
    {
      id: 'gravity-shift',
      title: '그래비티 시프트',
      titleEn: 'Gravity Shift',
      genre: '혁신적 게임플레이 · 퍼즐 플랫포머',
      status: 'demo',
      statusLabel: '데모',
      description: '중력 방향을 자유롭게 조작하여 전통적인 플랫폼 점프를 뒤집으세요. 뒤집힌 세계에서 탈출구를 찾으세요.',
      category: '혁신적 게임플레이',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'time-weaver',
      title: '타임 위버',
      titleEn: 'Time Weaver',
      genre: '혁신적 게임플레이 · 시간 조작',
      status: 'dev',
      statusLabel: '개발 중',
      description: '시간축을 조작하여 전투의 흐름을 바꾸세요. 모든 선택이 나비 효과를 일으켜 당신만의 운명을 엮어갑니다.',
      category: '혁신적 게임플레이',
    },
    {
      id: 'ink-soul',
      title: '잉크 소울',
      titleEn: 'Ink Soul',
      genre: '혁신적 게임플레이 · 수묵 액션',
      status: 'pv',
      statusLabel: 'PV',
      description: '수묵화 스타일과 창의적인 액션 시스템의 결합. 그림 두루마리 같은 세계에서 당신의 무협 전설을 써내려가세요.',
      category: '혁신적 게임플레이',
    },
    {
      id: 'frost-punk-tales',
      title: '프로스트펑크 테일즈',
      titleEn: 'Frost Punk Tales',
      genre: '포스트 아포칼립스 · 내러티브 어드벤처',
      status: 'released',
      statusLabel: '출시됨',
      description: '얼어붙은 황무지에서 마음 따뜻해지는 모험 여정을 떠나세요. 동북 공업 미학과 종말 내러티브의 충돌.',
      category: '포스트 아포칼립스 & 사이버 차이니즈',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'cipher-war',
      title: '사이퍼 워',
      titleEn: 'Cipher War',
      genre: '하드코어 전략 · 퍼즐',
      status: 'demo',
      statusLabel: '데모',
      description: '암호의 층을 풀어내고, 숫자와 논리의 미로에서 진실을 찾으세요. 두뇌를 태우는 퍼즐과 매력적인 스토리가 함께합니다.',
      category: '힐링 방치 & 하드코어 전략',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'dream-link',
      title: '드림 링크',
      titleEn: 'Dream Link',
      genre: '혁신적 게임플레이 · 협동',
      status: 'dev',
      statusLabel: '개발 중',
      description: '타인의 꿈속으로 들어가 독특한 연결 메커니즘으로 협력하여 퍼즐을 해결하세요. 잠재의식의 무한한 가능성을 탐험하세요.',
      category: '혁신적 게임플레이',
    },
  ],
  activities: [
    {
      id: 'ssca-2026',
      title: 'SSCA 애니메이션·코믹·게임 엑스포 · 게임 존',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2026-03-15',
      location: '선양',
      description: '페름프로스트 에코가 SSCA 선양 애니메이션·코믹·게임 엑스포에서 인디 게임 존을 운영. 동북 지역의 인디 게임 개발자에게 전시·교류 플랫폼을 제공하며 500명 이상의 개발자와 플레이어가 참여.',
      status: 'completed',
      images: [
        '/images/activities/ssca-2026-01.jpg',
        '/images/activities/ssca-2026-02.jpg',
        '/images/activities/ssca-2026-03.jpg',
      ],
    },
    {
      id: 'ggj-2026',
      title: 'Global Game Jam 2026 · 선양 사이트',
      titleEn: 'Global Game Jam 2026 · Shenyang Site',
      date: '2026-02',
      location: '선양 (온라인 + 오프라인)',
      description: '세계 최대 게임 창작 마라톤이 선양에 상륙. 48시간 동안 제로부터 게임 프로토타입을 제작하며 동북아시아의 가장 창의적인 개발자들이 집결.',
      status: 'completed',
      images: [
        '/images/activities/ggj-2026-01.jpg',
        '/images/activities/ggj-2026-02.jpg',
        '/images/activities/ggj-2026-03.jpg',
      ],
    },
    {
      id: 'beijing-expo-2026',
      title: '베이징 인디 게임 엑스포 2026',
      titleEn: 'Beijing Indie Game Expo 2026',
      date: '2026-05',
      location: '베이징',
      description: '페름프로스트 에코가 동북아시아 인디 게임 12작품을 가지고 베이징 인디 게임 엑스포에 출품. 지역 창작 역량을 보여주고 전국적인 협력 네트워크를 확장.',
      status: 'completed',
      images: [
        '/images/activities/beijing-expo-2026-01.jpg',
        '/images/activities/beijing-expo-2026-02.jpg',
      ],
    },
    {
      id: 'ciga-gamejam-2026-shenyang',
      title: '2026 CiGA Game Jam · 선양 사이트',
      titleEn: '2026 CiGA Game Jam · Shenyang Site',
      date: '2026-07',
      location: '선양',
      description: '중국 인디 게임 연합(CiGA)의 연례 Game Jam이 선양에 상륙. 48시간 창작 스프린트로 동북 지역의 가장 창의적인 게임 개발자들이 집결.',
      status: 'completed',
      images: [
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-01.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-02.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-03.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-04.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-05.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-06.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-07.webp',
      ],
    },
    {
      id: 'northern-anime-2026',
      title: '북경 애니메이션 게임 카니발 · 게임 존',
      titleEn: 'Northern Anime & Game Carnival · Game Zone',
      date: '2026-10',
      location: '선양',
      description: '북경 애니메이션 게임 카니발의 인디 게임 전용 존. 페름프로스트 에코가 공동 운영하며 동북아시아 인디 게임 개발자에게 전시와 교류의 장을 제공.',
      status: 'upcoming',
      highlight: true,
    },
    {
      id: 'ssca-2027',
      title: 'SSCA 애니메이션·코믹·게임 엑스포 · 게임 존',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2027-03',
      location: '선양',
      description: '페름프로스트 에코가 SSCA 선양 애니메이션·코믹·게임 엑스포에서 인디 게임 존을 운영. 동북 지역의 인디 게임 개발자에게 전시·교류 플랫폼을 제공.',
      status: 'upcoming',
    },
    {
      id: 'ggj-2027',
      title: 'Global Game Jam 2027 · 선양 사이트',
      titleEn: 'Global Game Jam 2027 · Shenyang Site',
      date: '2027-02',
      location: '선양',
      description: '세계 최대 게임 창작 마라톤이 다시 선양으로. 48시간 동안 제로부터 게임 프로토타입을 제작하며 동북아시아의 가장 창의적인 개발자들과 함께.',
      status: 'upcoming',
    },
  ],
  universities: [
    { id: 'neu', name: '둥베이대학', nameEn: 'Northeastern University', location: '선양' },
    { id: 'lnu', name: '랴오닝대학', nameEn: 'Liaoning University', location: '선양' },
    { id: 'dlut', name: '다롄이공대학', nameEn: 'Dalian University of Technology', location: '다롄' },
    { id: 'dlu', name: '다롄대학', nameEn: 'Dalian University', location: '다롄' },
    { id: 'jlu', name: '지린대학', nameEn: 'Jilin University', location: '창춘' },
    { id: 'nenu', name: '둥베이사범대학', nameEn: 'Northeast Normal University', location: '창춘' },
    { id: 'hit', name: '하얼빈공업대학', nameEn: 'Harbin Institute of Technology', location: '하얼빈' },
    { id: 'hrbeu', name: '하얼빈공정대학', nameEn: 'Harbin Engineering University', location: '하얼빈' },
    { id: 'imu', name: '내몽골대학', nameEn: 'Inner Mongolia University', location: '후허하오터' },
    { id: 'syau', name: '선양농업대학', nameEn: 'Shenyang Agricultural University', location: '선양' },
    { id: 'sut', name: '선양공업대학', nameEn: 'Shenyang University of Technology', location: '선양' },
    { id: 'dufe', name: '둥베이재경대학', nameEn: 'Dongbei University of Finance and Economics', location: '다롄' },
  ],
  partners: [
    {
      id: 'unity-china',
      name: 'Unity China',
      nameEn: 'Unity China',
      category: '엔진 기술',
      description: '세계를 선도하는 실시간 3D 콘텐츠 제작 플랫폼. 인디 게임 개발자에게 강력한 기술 지원과 생태계 리소스를 제공합니다.',
      logo: '/images/partners/unity.svg',
    },
    {
      id: 'netease-digital',
      name: 'NetEase 선양 디지털산업센터',
      nameEn: 'Netease Shenyang Digital Industry Center',
      category: '산업 인큐베이션',
      description: 'NetEase가 동북 지역에 설립한 디지털 산업 혁신 거점. 게임, 디지털 콘텐츠 및 기술 산업 인큐베이션에 주력.',
      logo: '/images/partners/netease-digital.svg',
    },
    {
      id: 'netease-edu',
      name: 'NetEase 게임 아카데미',
      nameEn: 'Netease Game Academy',
      category: '교육 육성',
      description: 'NetEase Games 산하 게임 인재 육성 플랫폼. 게임 디자인, 개발, 아트 등 전문 과정과 교육을 제공합니다.',
      logo: '/images/partners/netease-edu.svg',
    },
    {
      id: 'tencent-edu',
      name: 'Tencent 게임 아카데미',
      nameEn: 'Tencent Game Academy',
      category: '교육 육성',
      description: 'Tencent Games 산하 게임 인재 육성 및 학술 교류 플랫폼. 게임 산업 인재 발전에 전념.',
      logo: '/images/partners/tencent-edu.svg',
    },
    {
      id: 'asus-liaoning',
      name: 'ASUS 랴오닝',
      nameEn: 'ASUS Liaoning',
      category: '하드웨어',
      description: 'ASUS의 랴오닝 지역 지사. 게임 이벤트와 개발자에게 고성능 하드웨어 지원을 제공합니다.',
      logo: '/images/partners/asus.svg',
    },
    {
      id: 'aura',
      name: 'Aura',
      nameEn: 'Aura',
      category: '게이밍 기기',
      description: '유명 e스포츠 주변기기 브랜드. 인디 게임 개발자와 플레이어에게 전문가급 기기를 제공합니다.',
      logo: '/images/partners/aura.svg',
    },
  ],
  timelineEvents: [
    {
      year: '2024',
      title: '브랜드 창립',
      description: '페름프로스트 에코(Permafrost Echo) 브랜드가 선양에서 공식 설립. 동북아시아 인디 게임 생태계 플랫폼으로 자리매김.',
    },
    {
      year: '2025.03',
      title: '제1회 SSCA 엑스포 · 게임 존',
      description: '제1회 SSCA 선양 애니메이션·코믹·게임 엑스포에서 인디 게임 존을 운영. 200명 이상 참여.',
    },
    {
      year: '2025.08',
      title: '대학 연합 출범',
      description: '동북 지역 12개 대학과 연합하여 인디 게임 대학 연합을 설립. 캠퍼스 개발자 네트워크 구축.',
    },
    {
      year: '2026.02',
      title: 'GGJ 2026 선양 사이트',
      description: 'Global Game Jam 선양 사이트 첫 개최. 48시간 창작 마라톤 대성공.',
    },
    {
      year: '2026.03',
      title: 'SSCA 2026 엑스포 · 게임 존',
      description: 'SSCA 2026 규모 확대. 출품작 12개로 증가, 참여자 500명 돌파.',
    },
    {
      year: '2026.05',
      title: '베이징 엑스포 데뷔',
      description: '12개 작품을 가지고 베이징 인디 게임 엑스포에 첫 출품. 전국적 영향력 확대.',
    },
  ],
  roadmapPhases: [
    {
      phase: 'Phase 1',
      title: '브랜드 구축 및 커뮤니티 운영',
      items: [
        '페름프로스트 에코 브랜드 비주얼 체계 확립',
        'WeChat 및 QQ 커뮤니티 구축 (600명 이상)',
        '동북 12개 대학과 연합 결성',
        '제1회 SSCA 애니메이션·코믹·게임 엑스포 게임 존 운영',
      ],
      status: 'completed',
    },
    {
      phase: 'Phase 2',
      title: '이벤트 체계화 및 콘텐츠 제작',
      items: [
        'Game Jam 정기 개최 체계 확립 (연 2회)',
        '인디 게임 작품 인큐베이션 계획 시작',
        '심층 인터뷰 및 업계 분석 콘텐츠 제작',
        '파트너 네트워크 확대 (9개 이상 브랜드)',
      ],
      status: 'in-progress',
    },
    {
      phase: 'Phase 3',
      title: '지역 영향력 확장',
      items: [
        '동북아시아 19개 이상 대학 연합 커버',
        '제1회 페름프로스트 에코 인디 게임 전시회 개최',
        '개발자 커뮤니티 플랫폼 구축 (포럼/Wiki)',
        '지역 간 협력 프로젝트 시작 (한일러)',
      ],
      status: 'planned',
    },
    {
      phase: 'Phase 4',
      title: '생태계 플랫폼 구축',
      items: [
        '인디 게임 퍼블리싱 플랫폼 구축',
        '인디 게임 개발자 기금 설립',
        '국제급 인디 게임 페스티벌 개최',
        '동북아시아 최대 인디 게임 생태계 네트워크 구축',
      ],
      status: 'planned',
    },
  ],
};

const ruData: LocalizedData = {
  games: [
    {
      id: 'doomsday-traveler',
      title: 'Странник Судного Дня',
      titleEn: 'Doomsday Traveler',
      genre: 'Постапокалипсис · Выживание',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Исследуйте и выживайте в постапокалиптической пустоши, сочетая киберпанк-визуальный стиль с элементами традиционной китайской культуры для уникального опыта конца света.',
      category: 'Постапокалипсис & Кибер-китайский',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'phantom-blade',
      title: 'Хроники Призрачного Клинка',
      titleEn: 'Phantom Blade Chronicles',
      genre: 'Кибер-китайский · Экшен RPG',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Киберпанк-город встречает китайские боевые искусства. Быстрая боевая система и глубокое повествование.',
      category: 'Постапокалипсис & Кибер-китайский',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'neon-dynasty',
      title: 'Неоновая Династия',
      titleEn: 'Neon Dynasty',
      genre: 'Кибер-китайский · Стратегические карты',
      status: 'dev',
      statusLabel: 'В разработке',
      description: 'Стратегическая карточная игра, сочетающая традиционную китайскую живопись тушью с киберпанк-эстетикой. Планируйте ходы в неоновой древней столице.',
      category: 'Постапокалипсис & Кибер-китайский',
    },
    {
      id: 'star-garden',
      title: 'Звёздный Сад',
      titleEn: 'Star Garden',
      genre: 'Медитативный idle · Симулятор',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Создайте свой исцеляющий сад под звёздами, выращивайте экзотические растения и проводите время с очаровательными звёздными духами.',
      category: 'Медитативные & Хардкорные стратегии',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'void-chess',
      title: 'Шахматы Пустоты',
      titleEn: 'Void Chess',
      genre: 'Хардкорная стратегия · Тактические шахматы',
      status: 'released',
      statusLabel: 'Выпущено',
      description: 'Вступайте в интеллектуальные дуэли на шахматной доске пустоты. Оригинальная система правил открывает бесконечные стратегические возможности.',
      category: 'Медитативные & Хардкорные стратегии',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'echo-of-silence',
      title: 'Эхо Тишины',
      titleEn: 'Echo of Silence',
      genre: 'Медитативный idle · Музыкальный ритм',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Слушайте эхо в тишине, исцеляйте душу музыкой. Уникальный idle-геймплей в сочетании с оригинальной музыкой.',
      category: 'Медитативные & Хардкорные стратегии',
    },
    {
      id: 'gravity-shift',
      title: 'Гравитационный Сдвиг',
      titleEn: 'Gravity Shift',
      genre: 'Инновационный геймплей · Головоломка-платформер',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Переверните традиционные прыжки по платформам, свободно управляя направлением гравитации. Найдите выход в перевёрнутом мире.',
      category: 'Инновационный геймплей',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'time-weaver',
      title: 'Ткач Времени',
      titleEn: 'Time Weaver',
      genre: 'Инновационный геймплей · Манипуляция временем',
      status: 'dev',
      statusLabel: 'В разработке',
      description: 'Манипулируйте временной линией, чтобы изменить ход битвы. Каждый выбор создаёт эффект бабочки, сплетая вашу судьбу.',
      category: 'Инновационный геймплей',
    },
    {
      id: 'ink-soul',
      title: 'Душа Тушью',
      titleEn: 'Ink Soul',
      genre: 'Инновационный геймплей · Экшен в стиле туши',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Стиль живописи тушью в сочетании с креативной боевой системой. Напишите свою легенду боевых искусств в мире, похожем на живой свиток.',
      category: 'Инновационный геймплей',
    },
    {
      id: 'frost-punk-tales',
      title: 'Сказания Морозной Пустоши',
      titleEn: 'Frost Punk Tales',
      genre: 'Постапокалипсис · Нарративное приключение',
      status: 'released',
      statusLabel: 'Выпущено',
      description: 'Отправьтесь в трогательное приключение по замёрзшей пустоши. Столкновение северо-восточной индустриальной эстетики и постапокалиптического нарратива.',
      category: 'Постапокалипсис & Кибер-китайский',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'cipher-war',
      title: 'Шифровая Война',
      titleEn: 'Cipher War',
      genre: 'Хардкорная стратегия · Головоломка',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Взламывайте слои шифров и находите истину в лабиринте чисел и логики. Сложнейшие головоломки в сочетании с захватывающим сюжетом.',
      category: 'Медитативные & Хардкорные стратегии',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'dream-link',
      title: 'Связь Снов',
      titleEn: 'Dream Link',
      genre: 'Инновационный геймплей · Кооператив',
      status: 'dev',
      statusLabel: 'В разработке',
      description: 'Входите в сны других и решайте головоломки вместе с помощью уникального механизма связи. Исследуйте бесконечные возможности подсознания.',
      category: 'Инновационный геймплей',
    },
  ],
  activities: [
    {
      id: 'ssca-2026',
      title: 'SSCA Выставка аниме, комиксов и игр · Игровая зона',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2026-03-15',
      location: 'Шэньян',
      description: 'Permafrost Echo организует зону инди-игр на Шэньянской выставке аниме, комиксов и игр SSCA, предоставляя платформу для демонстрации и общения разработчикам инди-игр Северо-Восточного Китая, с участием более 500 разработчиков и игроков.',
      status: 'completed',
      images: [
        '/images/activities/ssca-2026-01.jpg',
        '/images/activities/ssca-2026-02.jpg',
        '/images/activities/ssca-2026-03.jpg',
      ],
    },
    {
      id: 'ggj-2026',
      title: 'Global Game Jam 2026 · Шэньян',
      titleEn: 'Global Game Jam 2026 · Shenyang Site',
      date: '2026-02',
      location: 'Шэньян (онлайн + офлайн)',
      description: 'Крупнейший в мире марафон по созданию игр проходит в Шэньяне. Создайте прототип игры с нуля за 48 часов вместе с самыми креативными разработчиками Северо-Восточной Азии.',
      status: 'completed',
      images: [
        '/images/activities/ggj-2026-01.jpg',
        '/images/activities/ggj-2026-02.jpg',
        '/images/activities/ggj-2026-03.jpg',
      ],
    },
    {
      id: 'beijing-expo-2026',
      title: 'Пекинская выставка инди-игр 2026',
      titleEn: 'Beijing Indie Game Expo 2026',
      date: '2026-05',
      location: 'Пекин',
      description: 'Permafrost Echo представляет 12 инди-игр Северо-Восточной Азии на Пекинской выставке инди-игр, демонстрируя творческую мощь региона и расширяя национальную сеть сотрудничества.',
      status: 'completed',
      images: [
        '/images/activities/beijing-expo-2026-01.jpg',
        '/images/activities/beijing-expo-2026-02.jpg',
      ],
    },
    {
      id: 'ciga-gamejam-2026-shenyang',
      title: '2026 CiGA Game Jam · Шэньян',
      titleEn: '2026 CiGA Game Jam · Shenyang Site',
      date: '2026-07',
      location: 'Шэньян',
      description: 'Ежегодный CiGA Game Jam проходит в Шэньяне. 48-часовой спринт творчества, объединяющий самых креативных разработчиков игр Северо-Восточного Китая.',
      status: 'completed',
      images: [
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-01.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-02.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-03.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-04.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-05.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-06.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-07.webp',
      ],
    },
    {
      id: 'northern-anime-2026',
      title: 'Северный аниме-игровой карнавал · Игровая зона',
      titleEn: 'Northern Anime & Game Carnival · Game Zone',
      date: '2026-10',
      location: 'Шэньян',
      description: 'Зона инди-игр Северного аниме-игрового карнавала, организованная совместно с Permafrost Echo, предоставляющая платформу для демонстрации и нетворкинга разработчиков инди-игр Северо-Восточной Азии.',
      status: 'upcoming',
      highlight: true,
    },
    {
      id: 'ssca-2027',
      title: 'SSCA Выставка аниме, комиксов и игр · Игровая зона',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2027-03',
      location: 'Шэньян',
      description: 'Permafrost Echo организует зону инди-игр на Шэньянской выставке аниме, комиксов и игр SSCA, предоставляя платформу для демонстрации и общения разработчикам инди-игр Северо-Восточного Китая.',
      status: 'upcoming',
    },
    {
      id: 'ggj-2027',
      title: 'Global Game Jam 2027 · Шэньян',
      titleEn: 'Global Game Jam 2027 · Shenyang Site',
      date: '2027-02',
      location: 'Шэньян',
      description: 'Крупнейший в мире марафон по созданию игр возвращается в Шэньян. Создайте прототип игры с нуля за 48 часов с самыми креативными разработчиками Северо-Восточной Азии.',
      status: 'upcoming',
    },
  ],
  universities: [
    { id: 'neu', name: 'Северо-Восточный университет', nameEn: 'Northeastern University', location: 'Шэньян' },
    { id: 'lnu', name: 'Ляонинский университет', nameEn: 'Liaoning University', location: 'Шэньян' },
    { id: 'dlut', name: 'Даляньский технологический университет', nameEn: 'Dalian University of Technology', location: 'Далянь' },
    { id: 'dlu', name: 'Даляньский университет', nameEn: 'Dalian University', location: 'Далянь' },
    { id: 'jlu', name: 'Цзилиньский университет', nameEn: 'Jilin University', location: 'Чанчунь' },
    { id: 'nenu', name: 'Северо-Восточный педагогический университет', nameEn: 'Northeast Normal University', location: 'Чанчунь' },
    { id: 'hit', name: 'Харбинский политехнический институт', nameEn: 'Harbin Institute of Technology', location: 'Харбин' },
    { id: 'hrbeu', name: 'Харбинский инженерный университет', nameEn: 'Harbin Engineering University', location: 'Харбин' },
    { id: 'imu', name: 'Университет Внутренней Монголии', nameEn: 'Inner Mongolia University', location: 'Хух-Хото' },
    { id: 'syau', name: 'Шэньянский сельскохозяйственный университет', nameEn: 'Shenyang Agricultural University', location: 'Шэньян' },
    { id: 'sut', name: 'Шэньянский технологический университет', nameEn: 'Shenyang University of Technology', location: 'Шэньян' },
    { id: 'dufe', name: 'Дунбэйский университет финансов и экономики', nameEn: 'Dongbei University of Finance and Economics', location: 'Далянь' },
  ],
  partners: [
    {
      id: 'unity-china',
      name: 'Unity China',
      nameEn: 'Unity China',
      category: 'Игровой движок',
      description: 'Ведущая в мире платформа для создания 3D-контента в реальном времени, предоставляющая мощную техническую поддержку и ресурсы экосистемы для разработчиков инди-игр.',
      logo: '/images/partners/unity.svg',
    },
    {
      id: 'netease-digital',
      name: 'Цифровой индустриальный центр NetEase в Шэньяне',
      nameEn: 'Netease Shenyang Digital Industry Center',
      category: 'Инкубация индустрии',
      description: 'Инновационная база цифровой индустрии NetEase в Северо-Восточном Китае, специализирующаяся на инкубации игр, цифрового контента и технологических отраслей.',
      logo: '/images/partners/netease-digital.svg',
    },
    {
      id: 'netease-edu',
      name: 'Игровая академия NetEase',
      nameEn: 'Netease Game Academy',
      category: 'Образование',
      description: 'Платформа подготовки кадров NetEase Games, предлагающая профессиональные курсы по геймдизайну, разработке и искусству.',
      logo: '/images/partners/netease-edu.svg',
    },
    {
      id: 'tencent-edu',
      name: 'Игровая академия Tencent',
      nameEn: 'Tencent Game Academy',
      category: 'Образование',
      description: 'Платформа подготовки кадров и академического обмена Tencent Games, посвящённая развитию талантов в игровой индустрии.',
      logo: '/images/partners/tencent-edu.svg',
    },
    {
      id: 'asus-liaoning',
      name: 'ASUS Ляонин',
      nameEn: 'ASUS Liaoning',
      category: 'Оборудование',
      description: 'Региональное отделение ASUS в Ляонине, обеспечивающее высокопроизводительную аппаратную поддержку для игровых мероприятий и разработчиков.',
      logo: '/images/partners/asus.svg',
    },
    {
      id: 'aura',
      name: 'Aura',
      nameEn: 'Aura',
      category: 'Игровая периферия',
      description: 'Известный бренд киберспортивной периферии, предоставляющий профессиональное оборудование для разработчиков инди-игр и игроков.',
      logo: '/images/partners/aura.svg',
    },
  ],
  timelineEvents: [
    {
      year: '2024',
      title: 'Основание бренда',
      description: 'Бренд Permafrost Echo официально основан в Шэньяне, позиционируется как платформа экосистемы инди-игр Северо-Восточной Азии.',
    },
    {
      year: '2025.03',
      title: 'Первая выставка SSCA · Игровая зона',
      description: 'Организована зона инди-игр на первой Шэньянской выставке аниме, комиксов и игр SSCA, привлекшая более 200 участников.',
    },
    {
      year: '2025.08',
      title: 'Запуск университетского альянса',
      description: 'Создан альянс инди-игр с 12 университетами Северо-Восточного Китая, построена сеть кампусных разработчиков.',
    },
    {
      year: '2026.02',
      title: 'GGJ 2026 Шэньян',
      description: 'Впервые проведён Global Game Jam в Шэньяне. 48-часовой марафон творчества прошёл с большим успехом.',
    },
    {
      year: '2026.03',
      title: 'SSCA 2026 Выставка · Игровая зона',
      description: 'SSCA 2026 масштабирована: 12 представленных проектов и более 500 участников игровой зоны.',
    },
    {
      year: '2026.05',
      title: 'Дебют на Пекинской выставке',
      description: 'Дебютировали на Пекинской выставке инди-игр с 12 проектами, расширяя национальное влияние.',
    },
  ],
  roadmapPhases: [
    {
      phase: 'Phase 1',
      title: 'Создание бренда и управление сообществом',
      items: [
        'Создание системы визуальной идентичности бренда Permafrost Echo',
        'Создание сообществ WeChat и QQ (600+ участников)',
        'Формирование альянса с 12 университетами Северо-Восточного Китая',
        'Организация игровой зоны на первой выставке аниме, комиксов и игр SSCA',
      ],
      status: 'completed',
    },
    {
      phase: 'Phase 2',
      title: 'Систематизация мероприятий и производство контента',
      items: [
        'Регулярное проведение Game Jam (2 раза в год)',
        'Запуск программы инкубации инди-игр',
        'Производство глубинных интервью и отраслевой аналитики',
        'Расширение партнёрской сети (9+ брендов)',
      ],
      status: 'in-progress',
    },
    {
      phase: 'Phase 3',
      title: 'Расширение регионального влияния',
      items: [
        'Охват 19+ университетских альянсов Северо-Восточной Азии',
        'Проведение первой выставки инди-игр Permafrost Echo',
        'Создание платформы сообщества разработчиков (форум/Wiki)',
        'Запуск межрегиональных проектов сотрудничества (Япония, Корея, Россия)',
      ],
      status: 'planned',
    },
    {
      phase: 'Phase 4',
      title: 'Построение экосистемной платформы',
      items: [
        'Создание платформы для издания инди-игр',
        'Учреждение фонда разработчиков инди-игр',
        'Проведение международного фестиваля инди-игр',
        'Построение крупнейшей сети экосистемы инди-игр в Северо-Восточной Азии',
      ],
      status: 'planned',
    },
  ],
};

const mnData: LocalizedData = {
  games: [
    {
      id: 'doomsday-traveler',
      title: 'Сүйрлийн Аялагч',
      titleEn: 'Doomsday Traveler',
      genre: 'Сүйрлийн дараах · Амьд үлдэх адал явдал',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Сүйрлийн дараах эзгүй газарт амьд үлдэж, киберпанк харааны хэв маягийг Хятадын уламжлалт соёлын элементүүдтэй хослуулан, өвөрмөц сүйрлийн туршлагыг бүтээнэ.',
      category: 'Сүйрлийн дараах & Кибер-Хятад',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'phantom-blade',
      title: 'Хий Үзэгдэл Ирний Түүх',
      titleEn: 'Phantom Blade Chronicles',
      genre: 'Кибер-Хятад · Экшн RPG',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Киберпанк хот Хятадын тулааны урлагтай мөргөлдөнө. Хурдан тулааны систем гүн гүнзгий өгүүллэгтэй хослоно.',
      category: 'Сүйрлийн дараах & Кибер-Хятад',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'neon-dynasty',
      title: 'Неон Угсаа',
      titleEn: 'Neon Dynasty',
      genre: 'Кибер-Хятад · Стратегийн хөзөр',
      status: 'dev',
      statusLabel: 'Хөгжүүлэлтэд',
      description: 'Хятадын уламжлалт бэхэн зургийн хэв маягийг киберпанк гоо зүйтэй хослуулсан стратегийн хөзрийн тоглоом. Неон гэрэлтэй эртний нийслэлд стратегиа боловсруул.',
      category: 'Сүйрлийн дараах & Кибер-Хятад',
    },
    {
      id: 'star-garden',
      title: 'Оддын Цэцэрлэг',
      titleEn: 'Star Garden',
      genre: 'Эдгээх Idle · Симуляци',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Оддын дор өөрийн эдгээх цэцэрлэгийг бий болгож, хачирхалтай ургамлууд тарьж, хөөрхөн одны сүнснүүдтэй тайван цагийг өнгөрүүлээрэй.',
      category: 'Эдгээх Idle & Хатуу Стратеги',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'void-chess',
      title: 'Хоосон Шатар',
      titleEn: 'Void Chess',
      genre: 'Хатуу Стратеги · Тактикийн шатар',
      status: 'released',
      statusLabel: 'Гарсан',
      description: 'Хоосон шатрын тавцан дээр өрсөлдөгчтэй оюуны тулаан хий. Анхны дүрмийн систем хязгааргүй стратегийн боломжийг нээнэ.',
      category: 'Эдгээх Idle & Хатуу Стратеги',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'echo-of-silence',
      title: 'Чимээгүйн Цуурай',
      titleEn: 'Echo of Silence',
      genre: 'Эдгээх Idle · Хөгжмийн хэмнэл',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Чимээгүй доторх цуурайг сонсож, хөгжмөөр сэтгэлээ эдгээ. Анхны idle тоглолтын туршлага анхны хөгжимтэй хослоно.',
      category: 'Эдгээх Idle & Хатуу Стратеги',
    },
    {
      id: 'gravity-shift',
      title: 'Таталцлын Шилжилт',
      titleEn: 'Gravity Shift',
      genre: 'Шинэлэг тоглолт · Тааварт платформер',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Таталцлын чиглэлийг чөлөөтэй удирдан, уламжлалт платформ үсрэлтийг эргүүл. Урвуу ертөнцөөс гарах замаа ол.',
      category: 'Шинэлэг Тоглолт',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'time-weaver',
      title: 'Цаг Нэхэгч',
      titleEn: 'Time Weaver',
      genre: 'Шинэлэг тоглолт · Цаг хугацааны удирдлага',
      status: 'dev',
      statusLabel: 'Хөгжүүлэлтэд',
      description: 'Тулааны явцыг өөрчлөхийн тулд цаг хугацааны шугамыг удирд. Сонголт бүр эрвээхэй нөлөө үүсгэж, хувь заяагаа нэхэнэ.',
      category: 'Шинэлэг Тоглолт',
    },
    {
      id: 'ink-soul',
      title: 'Бэхийн Сүнс',
      titleEn: 'Ink Soul',
      genre: 'Шинэлэг тоглолт · Бэхэн экшн',
      status: 'pv',
      statusLabel: 'PV',
      description: 'Бэхэн зургийн хэв маяг бүтээлч экшн системтэй хослоно. Амьд зураг мэт ертөнцөд тулааны урлагийн домгоо бич.',
      category: 'Шинэлэг Тоглолт',
    },
    {
      id: 'frost-punk-tales',
      title: 'Мөстлөгийн Түүхүүд',
      titleEn: 'Frost Punk Tales',
      genre: 'Сүйрлийн дараах · Өгүүллэгт адал явдал',
      status: 'released',
      statusLabel: 'Гарсан',
      description: 'Хөлдүү эзгүй газар дундуур сэтгэл дулаацуулах адал явдлын аянд гар. Зүүн хойд аж үйлдвэрийн гоо зүй ба сүйрлийн дараах өгүүллэгийн мөргөлдөөн.',
      category: 'Сүйрлийн дараах & Кибер-Хятад',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'cipher-war',
      title: 'Шифрын Дайн',
      titleEn: 'Cipher War',
      genre: 'Хатуу Стратеги · Таавар',
      status: 'demo',
      statusLabel: 'Демо',
      description: 'Давхар шифрүүдийг эвдэж, тоо ба логикийн төөрдөг байшинд үнэнийг ол. Тархи шатаах тааварууд сэтгэл татам өгүүллэгтэй зэрэгцэнэ.',
      category: 'Эдгээх Idle & Хатуу Стратеги',
      steamUrl: 'https://store.steampowered.com',
    },
    {
      id: 'dream-link',
      title: 'Зүүдний Холбоос',
      titleEn: 'Dream Link',
      genre: 'Шинэлэг тоглолт · Хамтын ажиллагаа',
      status: 'dev',
      statusLabel: 'Хөгжүүлэлтэд',
      description: 'Бусдын зүүдэнд нэвтэрч, өвөрмөц холбох механизмаар хамтран таавар шийд. Далд ухамсрын хязгааргүй боломжийг судал.',
      category: 'Шинэлэг Тоглолт',
    },
  ],
  activities: [
    {
      id: 'ssca-2026',
      title: 'SSCA Анимэ, Комик, Тоглоомын Үзэсгэлэн · Тоглоомын Бүс',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2026-03-15',
      location: 'Шэньян',
      description: 'Мөсөн Хөрсний Цуурай нь SSCA Шэньян Анимэ, Комик, Тоглоомын Үзэсгэлэн дээр инди тоглоомын бүс зохион байгуулж, Зүүн хойд Хятадын инди тоглоом хөгжүүлэгчдэд үзүүлэн, харилцааны платформ бий болгож, 500 гаруй хөгжүүлэгч, тоглогч оролцов.',
      status: 'completed',
      images: [
        '/images/activities/ssca-2026-01.jpg',
        '/images/activities/ssca-2026-02.jpg',
        '/images/activities/ssca-2026-03.jpg',
      ],
    },
    {
      id: 'ggj-2026',
      title: 'Global Game Jam 2026 · Шэньян',
      titleEn: 'Global Game Jam 2026 · Shenyang Site',
      date: '2026-02',
      location: 'Шэньян (онлайн + офлайн)',
      description: 'Дэлхийн хамгийн том тоглоом бүтээх марафон Шэньян хотод зохион байгуулагдлаа. 48 цагийн дотор тоглоомын прототипийг эхнээс нь бүтээж, Зүүн хойд Азийн хамгийн бүтээлч хөгжүүлэгчид цугларав.',
      status: 'completed',
      images: [
        '/images/activities/ggj-2026-01.jpg',
        '/images/activities/ggj-2026-02.jpg',
        '/images/activities/ggj-2026-03.jpg',
      ],
    },
    {
      id: 'beijing-expo-2026',
      title: 'Бээжин Инди Тоглоомын Экспо 2026',
      titleEn: 'Beijing Indie Game Expo 2026',
      date: '2026-05',
      location: 'Бээжин',
      description: 'Мөсөн Хөрсний Цуурай Зүүн хойд Азийн 12 инди тоглоомыг Бээжин Инди Тоглоомын Экспод авчирч, бүс нутгийн бүтээлч хүчийг харуулж, үндэсний хамтын ажиллагааны сүлжээг өргөжүүлэв.',
      status: 'completed',
      images: [
        '/images/activities/beijing-expo-2026-01.jpg',
        '/images/activities/beijing-expo-2026-02.jpg',
      ],
    },
    {
      id: 'ciga-gamejam-2026-shenyang',
      title: '2026 CiGA Game Jam · Шэньян',
      titleEn: '2026 CiGA Game Jam · Shenyang Site',
      date: '2026-07',
      location: 'Шэньян',
      description: 'Хятадын Инди Тоглоомын Холбооны (CiGA) жилийн Game Jam Шэньян хотод зохион байгуулагдлаа. 48 цагийн бүтээлийн спринт Зүүн хойд Хятадын хамгийн бүтээлч тоглоом хөгжүүлэгчдийг цуглуулав.',
      status: 'completed',
      images: [
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-01.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-02.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-03.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-04.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-05.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-06.webp',
        '/images/activities/ciga-gamejam-2026-shenyang/ciga-gamejam-2026-shenyang-07.webp',
      ],
    },
    {
      id: 'northern-anime-2026',
      title: 'Умард Анимэ Тоглоомын Баяр · Тоглоомын Бүс',
      titleEn: 'Northern Anime & Game Carnival · Game Zone',
      date: '2026-10',
      location: 'Шэньян',
      description: 'Умард Анимэ Тоглоомын Баярын инди тоглоомын тусгай бүс. Мөсөн Хөрсний Цуурай хамтран зохион байгуулж, Зүүн хойд Азийн инди тоглоом хөгжүүлэгчдэд үзүүлэн ба харилцааны тавцан бий болгоно.',
      status: 'upcoming',
      highlight: true,
    },
    {
      id: 'ssca-2027',
      title: 'SSCA Анимэ, Комик, Тоглоомын Үзэсгэлэн · Тоглоомын Бүс',
      titleEn: 'SSCA Animation, Comic & Game Expo · Game Zone',
      date: '2027-03',
      location: 'Шэньян',
      description: 'Мөсөн Хөрсний Цуурай нь SSCA Шэньян Анимэ, Комик, Тоглоомын Үзэсгэлэн дээр инди тоглоомын бүс зохион байгуулж, Зүүн хойд Хятадын инди тоглоом хөгжүүлэгчдэд үзүүлэн, харилцааны платформ бий болгоно.',
      status: 'upcoming',
    },
    {
      id: 'ggj-2027',
      title: 'Global Game Jam 2027 · Шэньян',
      titleEn: 'Global Game Jam 2027 · Shenyang Site',
      date: '2027-02',
      location: 'Шэньян',
      description: 'Дэлхийн хамгийн том тоглоом бүтээх марафон Шэньян хотод эргэн ирлээ. 48 цагийн дотор тоглоомын прототипийг эхнээс нь бүтээж, Зүүн хойд Азийн хамгийн бүтээлч хөгжүүлэгчидтэй хамт.',
      status: 'upcoming',
    },
  ],
  universities: [
    { id: 'neu', name: 'Зүүн Хойд Их Сургууль', nameEn: 'Northeastern University', location: 'Шэньян' },
    { id: 'lnu', name: 'Ляонин Их Сургууль', nameEn: 'Liaoning University', location: 'Шэньян' },
    { id: 'dlut', name: 'Далянь Технологийн Их Сургууль', nameEn: 'Dalian University of Technology', location: 'Далянь' },
    { id: 'dlu', name: 'Далянь Их Сургууль', nameEn: 'Dalian University', location: 'Далянь' },
    { id: 'jlu', name: 'Жилин Их Сургууль', nameEn: 'Jilin University', location: 'Чанчунь' },
    { id: 'nenu', name: 'Зүүн Хойд Багшийн Их Сургууль', nameEn: 'Northeast Normal University', location: 'Чанчунь' },
    { id: 'hit', name: 'Харбин Политехникийн Хүрээлэн', nameEn: 'Harbin Institute of Technology', location: 'Харбин' },
    { id: 'hrbeu', name: 'Харбин Инженерийн Их Сургууль', nameEn: 'Harbin Engineering University', location: 'Харбин' },
    { id: 'imu', name: 'Өвөр Монголын Их Сургууль', nameEn: 'Inner Mongolia University', location: 'Хөх хот' },
    { id: 'syau', name: 'Шэньян Хөдөө Аж Ахуйн Их Сургууль', nameEn: 'Shenyang Agricultural University', location: 'Шэньян' },
    { id: 'sut', name: 'Шэньян Технологийн Их Сургууль', nameEn: 'Shenyang University of Technology', location: 'Шэньян' },
    { id: 'dufe', name: 'Зүүн Хойд Санхүү Эдийн Засгийн Их Сургууль', nameEn: 'Dongbei University of Finance and Economics', location: 'Далянь' },
  ],
  partners: [
    {
      id: 'unity-china',
      name: 'Unity Хятад',
      nameEn: 'Unity China',
      category: 'Хөдөлгүүрийн технологи',
      description: 'Дэлхийд тэргүүлэгч бодит цагийн 3D контент бүтээх платформ. Инди тоглоом хөгжүүлэгчдэд хүчирхэг техникийн дэмжлэг ба экосистемийн нөөц үзүүлдэг.',
      logo: '/images/partners/unity.svg',
    },
    {
      id: 'netease-digital',
      name: 'NetEase Шэньян Дижитал Аж Үйлдвэрийн Төв',
      nameEn: 'Netease Shenyang Digital Industry Center',
      category: 'Аж үйлдвэрийн инкубаци',
      description: 'NetEase-ийн Зүүн хойд Хятадад байгуулсан дижитал аж үйлдвэрийн инновацийн бааз. Тоглоом, дижитал контент, технологийн аж үйлдвэрийн инкубацид төвлөрдөг.',
      logo: '/images/partners/netease-digital.svg',
    },
    {
      id: 'netease-edu',
      name: 'NetEase Тоглоомын Академи',
      nameEn: 'Netease Game Academy',
      category: 'Боловсрол ба сургалт',
      description: 'NetEase Games-ийн тоглоомын авьяас бэлтгэх платформ. Тоглоомын дизайн, хөгжүүлэлт, урлагийн мэргэжлийн сургалт явуулдаг.',
      logo: '/images/partners/netease-edu.svg',
    },
    {
      id: 'tencent-edu',
      name: 'Tencent Тоглоомын Академи',
      nameEn: 'Tencent Game Academy',
      category: 'Боловсрол ба сургалт',
      description: 'Tencent Games-ийн тоглоомын авьяас бэлтгэх ба эрдэм шинжилгээний солилцооны платформ. Тоглоомын салбарын авьяас хөгжилд зориулагдсан.',
      logo: '/images/partners/tencent-edu.svg',
    },
    {
      id: 'asus-liaoning',
      name: 'ASUS Ляонин',
      nameEn: 'ASUS Liaoning',
      category: 'Тоног төхөөрөмж',
      description: 'ASUS-ийн Ляонин дахь бүс нутгийн салбар. Тоглоомын арга хэмжээ болон хөгжүүлэгчдэд өндөр хүчин чадлын тоног төхөөрөмжийн дэмжлэг үзүүлдэг.',
      logo: '/images/partners/asus.svg',
    },
    {
      id: 'aura',
      name: 'Aura',
      nameEn: 'Aura',
      category: 'Тоглоомын дагалдах хэрэгсэл',
      description: 'Алдарт цахим спортын дагалдах хэрэгслийн брэнд. Инди тоглоом хөгжүүлэгчид болон тоглогчдод мэргэжлийн түвшний төхөөрөмж нийлүүлдэг.',
      logo: '/images/partners/aura.svg',
    },
  ],
  timelineEvents: [
    {
      year: '2024',
      title: 'Бренд үүсгэн байгуулагдсан',
      description: 'Мөсөн Хөрсний Цуурай (Permafrost Echo) бренд Шэньян хотод албан ёсоор байгуулагдаж, Зүүн хойд Азийн инди тоглоомын экосистемийн платформ болон байр сууриа тодорхойлов.',
    },
    {
      year: '2025.03',
      title: 'Анхны SSCA Үзэсгэлэн · Тоглоомын Бүс',
      description: 'Анхны SSCA Анимэ, Комик, Тоглоомын Үзэсгэлэн дээр инди тоглоомын бүс зохион байгуулж, 200+ оролцогч татав.',
    },
    {
      year: '2025.08',
      title: 'Их сургуулийн холбоо эхэлсэн',
      description: 'Зүүн хойд Хятадын 12 их сургуультай хамтран инди тоглоомын их сургуулийн холбоог байгуулж, кампусын хөгжүүлэгчдийн сүлжээг бий болгов.',
    },
    {
      year: '2026.02',
      title: 'GGJ 2026 Шэньян',
      description: 'Global Game Jam Шэньян хотын цэгийг анх удаа зохион байгуулав. 48 цагийн бүтээлийн марафон амжилттай болж өндөрлөв.',
    },
    {
      year: '2026.03',
      title: 'SSCA 2026 Үзэсгэлэн · Тоглоомын Бүс',
      description: 'SSCA 2026 цар хүрээгээ тэлж, үзүүлсэн бүтээл 12 болж, оролцогчид 500-г давлаа.',
    },
    {
      year: '2026.05',
      title: 'Бээжин Экспод анхны оролцоо',
      description: '12 бүтээлтэйгээр Бээжин Инди Тоглоомын Экспод анх удаа оролцож, үндэсний хэмжээний нөлөөгөө тэлэв.',
    },
  ],
  roadmapPhases: [
    {
      phase: 'Phase 1',
      title: 'Бренд бий болголт ба нийгэмлэгийн үйл ажиллагаа',
      items: [
        'Мөсөн Хөрсний Цуурай брендийн харааны таних тогтолцоог бий болгох',
        'WeChat болон QQ нийгэмлэгүүдийг байгуулах (600+ гишүүн)',
        'Зүүн хойд Хятадын 12 их сургуультай холбоо байгуулах',
        'Анхны SSCA Анимэ, Комик, Тоглоомын Үзэсгэлэнгийн тоглоомын бүс зохион байгуулах',
      ],
      status: 'completed',
    },
    {
      phase: 'Phase 2',
      title: 'Арга хэмжээний системчлэл ба контент үйлдвэрлэл',
      items: [
        'Game Jam тогтмол зохион байгуулах механизмыг бий болгох (жилд 2 удаа)',
        'Инди тоглоом бүтээлийн инкубацийн төлөвлөгөөг эхлүүлэх',
        'Гүнзгий ярилцлага ба салбарын шинжилгээний контент үйлдвэрлэх',
        'Түншлэлийн сүлжээг өргөжүүлэх (9+ брэнд)',
      ],
      status: 'in-progress',
    },
    {
      phase: 'Phase 3',
      title: 'Бүс нутгийн нөлөөг тэлэх',
      items: [
        'Зүүн хойд Азийн 19+ их сургуулийн холбоог хамрах',
        'Анхны Мөсөн Хөрсний Цуурай Инди Тоглоомын Үзэсгэлэнг зохион байгуулах',
        'Хөгжүүлэгчдийн нийгэмлэгийн платформыг байгуулах (Форум/Вики)',
        'Бүс нутаг хоорондын хамтын ажиллагааны төслүүдийг эхлүүлэх (Япон, Солонгос, Орос)',
      ],
      status: 'planned',
    },
    {
      phase: 'Phase 4',
      title: 'Экосистемийн платформ байгуулалт',
      items: [
        'Инди тоглоом хэвлэлтийн платформыг байгуулах',
        'Инди тоглоом хөгжүүлэгчдийн санг бий болгох',
        'Олон улсын түвшний инди тоглоомын наадмыг зохион байгуулах',
        'Зүүн хойд Азийн хамгийн том инди тоглоомын экосистемийн сүлжээг байгуулах',
      ],
      status: 'planned',
    },
  ],
};

const dataMap: Record<Locale, LocalizedData> = {
  zh: zhData,
  en: enData,
  ja: jaData,
  ko: koData,
  ru: ruData,
  mn: mnData,
};

function getData(locale: Locale): LocalizedData {
  return dataMap[locale] || zhData;
}

// ============ 导出函数（需要传入 locale） ============

export function getGames(locale?: Locale): GameInfo[] {
  const data = getData(locale || 'zh');
  return data.games;
}

export function getGamesByCategory(category: string, locale?: Locale): GameInfo[] {
  const data = getData(locale || 'zh');
  return data.games.filter((g) => g.category === category);
}

export function getFeaturedGames(locale?: Locale): GameInfo[] {
  const data = getData(locale || 'zh');
  return data.games.slice(0, 4);
}

export function getActivities(locale?: Locale): ActivityInfo[] {
  const data = getData(locale || 'zh');
  return data.activities;
}

export function getUpcomingActivities(locale?: Locale): ActivityInfo[] {
  const data = getData(locale || 'zh');
  return data.activities.filter((a) => a.status === 'upcoming');
}

export function getCompletedActivities(locale?: Locale): ActivityInfo[] {
  const data = getData(locale || 'zh');
  return data.activities.filter((a) => a.status === 'completed');
}

export function getUniversities(locale?: Locale): UniversityInfo[] {
  const data = getData(locale || 'zh');
  return data.universities;
}

export function getPartners(locale?: Locale): PartnerInfo[] {
  const data = getData(locale || 'zh');
  return data.partners;
}

export function getTimelineEvents(locale?: Locale): TimelineEvent[] {
  const data = getData(locale || 'zh');
  return data.timelineEvents;
}

export function getRoadmapPhases(locale?: Locale): RoadmapPhase[] {
  const data = getData(locale || 'zh');
  return data.roadmapPhases;
}

export function getStats() {
  return {
    members: 1000,
    universities: 20,
    games: 30,
    years: 4,
    partners: 9,
    events: 6,
  };
}
